import os
from pathlib import Path
from fastapi import FastAPI, Depends, Request
from fastapi.middleware.cors import CORSMiddleware
from starlette.middleware.sessions import SessionMiddleware
from sqlalchemy.orm import Session
from dotenv import load_dotenv

# 1. LOAD ENVIRONMENT VARIABLES
# Using Path(__file__) ensures the .env is found regardless of where you start uvicorn
env_path = Path(__file__).resolve().parent / ".env"
load_dotenv(dotenv_path=env_path)

# DEBUG: Verify the keys are loading (Look in your backend terminal)
print(f"DEBUG: Google ID is {os.getenv('GOOGLE_CLIENT_ID')}")

# 2. IMPORT INTERNAL MODULES
# Using absolute imports (no dots) to prevent 'ImportError'
from auth import auth_router
from database import get_db, engine
from models import User, UserStats, UsedWords, Base

# Create tables
Base.metadata.create_all(bind=engine)

app = FastAPI(title="Quickle Wordle Backend")

# 3. SESSION MIDDLEWARE
# Must be added BEFORE including the auth_router. 
# Uses a fallback key if the .env variable is missing to prevent TypeError.
app.add_middleware(
    SessionMiddleware, 
    secret_key=os.getenv("SESSION_SECRET_KEY", "temporary_dev_secret_123")
)

# 4. CORS MIDDLEWARE
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# 5. INCLUDE ROUTERS
app.include_router(auth_router)

# --- GAME LOGIC & WORD LIST ---

# Valid 5-letter words that can be guessed (comprehensive list)
VALID_GUESSES = [
    "ABOUT", "ABOVE", "ABUSE", "ACTOR", "ACUTE", "ADMIT", "ADOPT", "ADULT", "AFTER", "AGAIN",
    "AGENT", "AGREE", "AHEAD", "ALARM", "ALBUM", "ALERT", "ALIEN", "ALIGN", "ALIKE", "ALIVE",
    "ALLOW", "ALONE", "ALONG", "ALTER", "AMONG", "ANGER", "ANGLE", "ANGRY", "APART", "APPLE",
    "APPLY", "ARENA", "ARGUE", "ARISE", "ARMED", "ARMOR", "ARRAY", "ASIDE", "ASSET", "AVOID",
    "AWAKE", "AWARD", "AWARE", "BADLY", "BAKER", "BASES", "BASIC", "BEACH", "BEGAN", "BEGIN",
    "BEING", "BELOW", "BENCH", "BILLY", "BIRTH", "BLACK", "BLAME", "BLANK", "BLAST", "BLIND",
    "BLOCK", "BLOOD", "BOARD", "BOOST", "BOOTH", "BOUND", "BRAIN", "BRAND", "BRASS", "BRAVE",
    "BREAD", "BREAK", "BREED", "BRIEF", "BRING", "BROAD", "BROKE", "BROWN", "BUILD", "BUILT",
    "BUYER", "CABLE", "CALIF", "CARRY", "CATCH", "CAUSE", "CHAIN", "CHAIR", "CHAOS", "CHARM",
    "CHART", "CHASE", "CHEAP", "CHECK", "CHEST", "CHIEF", "CHILD", "CHINA", "CHOSE", "CIVIL",
    "CLAIM", "CLASS", "CLEAN", "CLEAR", "CLICK", "CLIMB", "CLOCK", "CLOSE", "CLOUD", "COACH",
    "COAST", "COULD", "COUNT", "COURT", "COVER", "CRAFT", "CRASH", "CRAZY", "CREAM", "CRIME",
    "CROSS", "CROWD", "CROWN", "CRUDE", "CURVE", "CYCLE", "DAILY", "DANCE", "DATED", "DEALT",
    "DEATH", "DEBUT", "DELAY", "DEPTH", "DOING", "DOUBT", "DOZEN", "DRAFT", "DRAMA", "DRANK",
    "DRAWN", "DREAM", "DRESS", "DRILL", "DRINK", "DRIVE", "DROVE", "DYING", "EAGER", "EARLY",
    "EARTH", "EIGHT", "ELITE", "EMPTY", "ENEMY", "ENJOY", "ENTER", "ENTRY", "EQUAL", "ERROR",
    "EVENT", "EVERY", "EXACT", "EXIST", "EXTRA", "FAITH", "FALSE", "FAULT", "FIBER", "FIELD",
    "FIFTH", "FIFTY", "FIGHT", "FINAL", "FIRST", "FIXED", "FLASH", "FLEET", "FLOOR", "FLUID",
    "FOCUS", "FORCE", "FORTH", "FORTY", "FORUM", "FOUND", "FRAME", "FRANK", "FRAUD", "FRESH",
    "FRONT", "FRUIT", "FULLY", "FUNNY", "GIANT", "GIVEN", "GLASS", "GLOBE", "GOING", "GRACE",
    "GRADE", "GRAND", "GRANT", "GRASS", "GRAVE", "GREAT", "GREEN", "GROSS", "GROUP", "GROWN",
    "GUARD", "GUESS", "GUEST", "GUIDE", "HAPPY", "HARRY", "HEART", "HEAVY", "HELLO", "HENCE",
    "HENRY", "HORSE", "HOTEL", "HOUSE", "HUMAN", "IDEAL", "IMAGE", "INDEX", "INNER", "INPUT",
    "ISSUE", "JAPAN", "JIMMY", "JOINT", "JONES", "JUDGE", "KNOWN", "LABEL", "LARGE", "LASER",
    "LATER", "LAUGH", "LAYER", "LEARN", "LEASE", "LEAST", "LEAVE", "LEGAL", "LEVEL", "LEWIS",
    "LIGHT", "LIMIT", "LINKS", "LIVES", "LOCAL", "LOOSE", "LOWER", "LUCKY", "LUNCH", "LYING",
    "MAGIC", "MAJOR", "MAKER", "MARCH", "MARIA", "MATCH", "MAYBE", "MAYOR", "MEANT", "MEDIA",
    "METAL", "MIGHT", "MINOR", "MINUS", "MIXED", "MODEL", "MONEY", "MONTH", "MORAL", "MOTOR",
    "MOUNT", "MOUSE", "MOUTH", "MOVED", "MOVIE", "MUSIC", "NEEDS", "NEVER", "NEWLY", "NIGHT",
    "NOISE", "NORTH", "NOTED", "NOVEL", "NURSE", "OCCUR", "OCEAN", "OFFER", "OFTEN", "ORDER",
    "OTHER", "OUGHT", "PAINT", "PANEL", "PAPER", "PARTY", "PEACE", "PETER", "PHASE", "PHONE",
    "PHOTO", "PIANO", "PIECE", "PILOT", "PITCH", "PLACE", "PLAIN", "PLANE", "PLANT", "PLATE",
    "POINT", "POUND", "POWER", "PRESS", "PRICE", "PRIDE", "PRIME", "PRINT", "PRIOR", "PRIZE",
    "PROOF", "PROUD", "PROVE", "QUEEN", "QUICK", "QUIET", "QUITE", "RADIO", "RAISE", "RANGE",
    "RAPID", "RATIO", "REACH", "READY", "REALM", "REBEL", "REFER", "RELAX", "RIDER", "RIDGE",
    "RIGHT", "RIGID", "RIVAL", "RIVER", "ROBOT", "ROMAN", "ROUGH", "ROUND", "ROUTE", "ROYAL",
    "RURAL", "SCALE", "SCENE", "SCOPE", "SCORE", "SENSE", "SERVE", "SEVEN", "SHALL", "SHAPE",
    "SHARE", "SHARP", "SHEET", "SHELF", "SHELL", "SHIFT", "SHINE", "SHIRT", "SHOCK", "SHOOT",
    "SHORT", "SHOWN", "SIDED", "SIGHT", "SILLY", "SIMIL", "SINCE", "SIXTH", "SIXTY", "SIZED",
    "SKILL", "SLEEP", "SLIDE", "SMALL", "SMART", "SMILE", "SMITH", "SMOKE", "SNAKE", "SNOWY",
    "SOLID", "SOLVE", "SORRY", "SOUND", "SOUTH", "SPACE", "SPARE", "SPEAK", "SPEED", "SPEND",
    "SPENT", "SPLIT", "SPOKE", "SPORT", "SQUAD", "STAFF", "STAGE", "STAKE", "STAND", "START",
    "STATE", "STEAM", "STEEL", "STICK", "STILL", "STOCK", "STONE", "STOOD", "STORE", "STORM",
    "STORY", "STRIP", "STUCK", "STUDY", "STUFF", "STYLE", "SUGAR", "SUITE", "SUPER", "SWEET",
    "TABLE", "TAKEN", "TASTE", "TAXES", "TEACH", "TEETH", "TERRY", "TEXAS", "THANK", "THEFT",
    "THEIR", "THEME", "THERE", "THESE", "THICK", "THING", "THINK", "THIRD", "THOSE", "THREE",
    "THREW", "THROW", "THUMB", "TIGER", "TIGHT", "TIRED", "TITLE", "TODAY", "TOKEN", "TOPIC",
    "TOTAL", "TOUCH", "TOUGH", "TOWER", "TRACK", "TRADE", "TRAIL", "TRAIN", "TRAIT", "TREND",
    "TRIAL", "TRIBE", "TRICK", "TRIED", "TRIES", "TRUCK", "TRULY", "TRUNK", "TRUST", "TRUTH",
    "TWICE", "TWIST", "TYLER", "ULTRA", "UNCLE", "UNDER", "UNDUE", "UNION", "UNITY", "UNTIL",
    "UPPER", "UPSET", "URBAN", "USAGE", "USUAL", "VALUE", "VIDEO", "VIRAL", "VIRUS", "VISIT",
    "VITAL", "VOCAL", "VOICE", "WASTE", "WATCH", "WATER", "WHEEL", "WHERE", "WHICH", "WHILE",
    "WHITE", "WHOLE", "WHOSE", "WOMAN", "WOMEN", "WORLD", "WORRY", "WORSE", "WORST", "WORTH",
    "WOULD", "WRITE", "WRONG", "WROTE", "YOUNG", "YOUTH",
    # Additional comprehensive 5-letter words
    "ABACK", "ABASE", "ABATE", "ABBEY", "ABBOT", "ABHOR", "ABIDE", "ABODE", "ABORT", "ABOUND",
    "ABUSE", "ABYSS", "ACORN", "ACRID", "ACTED", "ACTIN", "ACTOR", "ACUTE", "ADAGE", "ADAPT",
    "ADEPT", "ADMIN", "ADMIT", "ADOBE", "ADOPT", "ADORE", "ADORN", "ADULT", "AFFIX", "AFIRE",
    "AFOOT", "AFORE", "AFRESH", "AGATE", "AGAVE", "AGENT", "AGILE", "AGING", "AGLOW", "AGONY",
    "AGREE", "AHEAD", "AIDER", "AIDES", "AILED", "AIMED", "AIRED", "AISLE", "ALARM", "ALBUM",
    "ALERT", "ALGAE", "ALIBI", "ALIEN", "ALIGN", "ALIKE", "ALIVE", "ALLAY", "ALLEY", "ALLOT",
    "ALLOW", "ALLOY", "ALOFT", "ALONE", "ALONG", "ALOOF", "ALoud", "ALPHA", "ALTAR", "ALTER",
    "AMASS", "AMBER", "AMBLE", "AMEND", "AMISS", "AMITY", "AMONG", "AMPLE", "AMPLY", "AMUSE",
    "ANGEL", "ANGER", "ANGLE", "ANGRY", "ANGST", "ANIME", "ANKLE", "ANNEX", "ANNOY", "ANNUL",
    "ANODE", "ANTIC", "ANVIL", "AORTA", "APART", "APHID", "APING", "APNEA", "APPLE", "APPLY",
    "ARENA", "ARGUE", "ARISE", "ARMED", "ARMOR", "AROMA", "AROSE", "ARRAY", "ARROW", "ARSON",
    "ARTSY", "ASCOT", "ASHEN", "ASIDE", "ASKEW", "ASSAY", "ASSET", "ATOLL", "ATONE", "ATTIC",
    "AUDIO", "AUDIT", "AUGUR", "AUNTY", "AVAIL", "AVERT", "AVIAN", "AVOID", "AWAIT", "AWAKE",
    "AWARD", "AWARE", "AWASH", "AWFUL", "AWOKE", "AXIAL", "AXIOM", "AXLES", "AZURE", "BACON",
    "BADGE", "BADLY", "BAGEL", "BAILY", "BAKER", "BALER", "BALMY", "BANAL", "BANJO", "BARGE",
    "BARON", "BASAL", "BASIC", "BASIL", "BASIN", "BASIS", "BASTE", "BATCH", "BATHE", "BATON",
    "BATTY", "BAWLS", "BEACH", "BEADS", "BEADY", "BEAMS", "BEAMY", "BEARS", "BEAST", "BEATS",
    "BEGAN", "BEGAT", "BEGET", "BEGIN", "BEGUN", "BEING", "BELCH", "BELIE", "BELLE", "BELLS",
    "BERET", "BERTH", "BESET", "BESTS", "BETEL", "BEVEL", "BEZEL", "BIBLE", "BICEP", "BIDDY",
    "BIGOT", "BILGE", "BILLY", "BINGE", "BINGO", "BIOME", "BIRCH", "BIRDS", "BIRTH", "BISON",
    "BITTY", "BLACK", "BLADE", "BLAME", "BLAND", "BLANK", "BLARE", "BLAST", "BLAZE", "BLEAK",
    "BLEAT", "BLEED", "BLEEP", "BLEND", "BLESS", "BLIMP", "BLIND", "BLINK", "BLISS", "BLITZ",
    "BLOAT", "BLOCK", "BLOKE", "BLOND", "BLOOD", "BLOOM", "BLOWN", "BLUES", "BLUFF", "BLUNT",
    "BLURB", "BLURT", "BLUSH", "BOARD", "BOAST", "BOATS", "BOBBY", "BODES", "BOILS", "BOING",
    "BOLTS", "BONDS", "BONED", "BONER", "BONGS", "BONUS", "BOOBY", "BOOST", "BOOTH", "BOOTS",
    "BOOTY", "BOOZE", "BOOZY", "BORAX", "BORNE", "BOSOM", "BOSON", "BOTCH", "BOUGH", "BOULE",
    "BOUND", "BOWEL", "BOWER", "BOXED", "BOXER", "BOXES", "BRACE", "BRAID", "BRAIN", "BRAKE",
    "BRAND", "BRASH", "BRASS", "BRAVE", "BRAVO", "BRAWL", "BRAWN", "BRAYS", "BRAZE", "BREAD",
    "BREAK", "BREED", "BREVE", "BRIBE", "BRICK", "BRIDE", "BRIEF", "BRINE", "BRING", "BRINK",
    "BRINY", "BRISK", "BROAD", "BROIL", "BROKE", "BROOD", "BROOK", "BROOM", "BROTH", "BROWN",
    "BRUNT", "BRUSH", "BRUTE", "BUDDY", "BUDGE", "BUGGY", "BUGLE", "BUILD", "BUILT", "BULBS",
    "BULGE", "BULKY", "BULLY", "BUMPS", "BUMPY", "BUNCH", "BUNNY", "BURNT", "BURST", "BUSED",
    "BUSHY", "BUTCH", "BUTTE", "BUXOM", "BUYER", "BYLAW", "CABAL", "CABBY", "CABIN", "CABLE",
    "CACAO", "CACHE", "CACTI", "CADDY", "CADET", "CAGEY", "CAIRN", "CAKES", "CALFS", "CALLS",
    "CALMS", "CAMEL", "CAMEO", "CANAL", "CANDY", "CANED", "CANES", "CANNY", "CANOE", "CANON",
    "CAPER", "CAPES", "CARAT", "CARGO", "CAROL", "CARRY", "CARVE", "CASED", "CASES", "CASTE",
    "CASTS", "CATCH", "CATER", "CATTY", "CAULK", "CAUSE", "CAVED", "CAVES", "CEASE", "CEDAR",
    "CEDED", "CELEB", "CELLS", "CENTS", "CHAFE", "CHAFF", "CHAIN", "CHAIR", "CHAIR", "CHALK",
    "CHAMP", "CHANT", "CHAOS", "CHARM", "CHART", "CHASE", "CHASM", "CHEAP", "CHEAT", "CHECK",
    "CHEEK", "CHEER", "CHEFS", "CHESS", "CHEST", "CHICK", "CHIEF", "CHILD", "CHILI", "CHILL",
    "CHIME", "CHINA", "CHIRP", "CHOCK", "CHOIR", "CHOKE", "CHORD", "CHORE", "CHOSE", "CHUCK",
    "CHUMP", "CHUNK", "CHURN", "CHUTE", "CIDER", "CIGAR", "CINCH", "CIRCA", "CITED", "CITES",
    "CIVET", "CIVIC", "CIVIL", "CLACK", "CLAIM", "CLAMP", "CLANG", "CLANK", "CLASH", "CLASP",
    "CLASS", "CLEAN", "CLEAR", "CLEAT", "CLEFS", "CLEFT", "CLERK", "CLICK", "CLIFF", "CLIMB",
    "CLING", "CLINK", "CLOAK", "CLOCK", "CLONE", "CLOSE", "CLOTH", "CLOUD", "CLOUT", "CLOVE",
    "CLOWN", "CLUBS", "CLUCK", "CLUED", "CLUES", "CLUMP", "CLUNG", "COACH", "COALS", "COAST",
    "COBRA", "COCOA", "CODED", "CODES", "COILS", "COINS", "COLDS", "COLON", "COLTS", "COMBO",
    "COMES", "COMET", "COMFY", "COMIC", "COMMA", "CONCH", "CONDO", "CONIC", "COPSE", "CORAL",
    "CORER", "CORNY", "COSTS", "COUCH", "COUGH", "COULD", "COUNT", "COUPE", "COURT", "COVEN",
    "COVER", "COVET", "COVEY", "COWER", "COYLY", "CRABS", "CRACK", "CRAFT", "CRAMP", "CRANE",
    "CRANK", "CRASH", "CRASS", "CRATE", "CRAVE", "CRAWL", "CRAZE", "CRAZY", "CREAK", "CREAM",
    "CREDO", "CREED", "CREEK", "CREEP", "CREME", "CREPE", "CREPT", "CRESS", "CREST", "CRICK",
    "CRIED", "CRIES", "CRIME", "CRIMP", "CRISP", "CROAK", "CROCK", "CRONE", "CRONY", "CROOK",
    "CROSS", "CROUP", "CROWD", "CROWN", "CRUDE", "CRUEL", "CRUMB", "CRUMP", "CRUSH", "CRUST",
    "CRYPT", "CUBIC", "CUMIN", "CUPID", "CURED", "CURES", "CURIO", "CURLS", "CURLY", "CURRY",
    "CURSE", "CURVE", "CURVY", "CUTIE", "CYCLE", "CYNIC", "DABBA", "DAILY", "DAIRY", "DAISY",
    "DALES", "DAMES", "DAMNS", "DANCE", "DANDY", "DATED", "DAUNT", "DAVIT", "DAWNS", "DEALS",
    "DEALT", "DEATH", "DEBAR", "DEBIT", "DEBUG", "DEBUT", "DECAL", "DECAY", "DECOR", "DECOY",
    "DECRY", "DEFER", "DEIGN", "DEITY", "DELAY", "DELTA", "DELVE", "DEMON", "DEMOS", "DENIM",
    "DENSE", "DEPOT", "DEPTH", "DERBY", "DETER", "DETOX", "DEUCE", "DEVIL", "DIARY", "DICED",
    "DICES", "DIGIT", "DILLY", "DIMLY", "DINER", "DINGO", "DINGY", "DIODE", "DIRGE", "DIRTY",
    "DISCO", "DITCH", "DITTO", "DITTY", "DIVER", "DIZZY", "DODGE", "DODGY", "DOGGY", "DOGMA",
    "DOING", "DOLLY", "DONOR", "DONUT", "DOPEY", "DOUBT", "DOUSE", "DOVER", "DOWEL", "DOWNY",
    "DOZEN", "DRAFT", "DRAGS", "DRAIN", "DRAKE", "DRAMA", "DRANK", "DRAPE", "DRAWL", "DRAWN",
    "DRAWS", "DREAD", "DREAM", "DRESS", "DRIED", "DRIER", "DRIES", "DRIFT", "DRILL", "DRINK",
    "DRIVE", "DROIT", "DROLL", "DRONE", "DROOL", "DROOP", "DROPS", "DROSS", "DROVE", "DROWN",
    "DRUID", "DRUMS", "DRUNK", "DRYER", "DRYLY", "DUCHY", "DULLS", "DUMMY", "DUMPS", "DUMPY",
    "DUNCE", "DUSKY", "DUSTY", "DUTCH", "DUVET", "DWARF", "DWELL", "DWELT", "DYING", "EAGER",
    "EAGLE", "EARLY", "EARTH", "EASED", "EASEL", "EASES", "EATEN", "EATER", "EAVES", "EBBED",
    "EBONY", "EDEMA", "EDGED", "EDGES", "EDICT", "EDIFY", "EERIE", "EGGED", "EGRET", "EIDER",
    "EIGHT", "EJECT", "EKING", "ELATE", "ELBOW", "ELDER", "ELECT", "ELEGY", "ELFIN", "ELIDE",
    "ELITE", "ELOPE", "ELUDE", "EMAIL", "EMBED", "EMBER", "EMCEE", "EMPTY", "ENACT", "ENDED",
    "ENDOW", "ENEMA", "ENEMY", "ENJOY", "ENNUI", "ENSUE", "ENTER", "ENTRY", "ENVOY", "EPOCH",
    "EPOXY", "EQUAL", "EQUIP", "ERASE", "ERECT", "ERODE", "ERROR", "ERUPT", "ESSAY", "ESTER",
    "ETHER", "ETHIC", "ETHOS", "ETUDE", "EVADE", "EVENT", "EVERY", "EVICT", "EVOKE", "EXACT",
    "EXALT", "EXCEL", "EXERT", "EXILE", "EXIST", "EXITS", "EXPAT", "EXPEL", "EXTOL", "EXTRA",
    "EXULT", "EYING", "FABLE", "FACED", "FACES", "FACET", "FACIE", "FAILS", "FAINT", "FAIRY",
    "FAITH", "FAKED", "FAKER", "FAKES", "FALSE", "FANCY", "FANGS", "FANNY", "FARCE", "FATAL",
    "FATED", "FATTY", "FAULT", "FAUNA", "FAVES", "FEAST", "FEATS", "FECAL", "FEIGN", "FELLA",
    "FELON", "FEMME", "FEMUR", "FENCE", "FERAL", "FERRY", "FETAL", "FETCH", "FETID", "FETUS",
    "FEVER", "FEWER", "FIBER", "FIBRE", "FICUS", "FIELD", "FIEND", "FIERY", "FIFES", "FIFTH",
    "FIFTY", "FIGHT", "FILER", "FILES", "FILLY", "FILMS", "FILMY", "FILTH", "FINAL", "FINCH",
    "FINER", "FINES", "FINIS", "FINKS", "FIORD", "FIRED", "FIRES", "FIRMS", "FIRST", "FISHY",
    "FIXED", "FIXER", "FIXES", "FIZZY", "FJORD", "FLACK", "FLAIL", "FLAIR", "FLAKE", "FLAKY",
    "FLAME", "FLANK", "FLAPS", "FLARE", "FLASH", "FLASK", "FLECK", "FLEET", "FLESH", "FLICK",
    "FLIED", "FLIER", "FLIES", "FLING", "FLINT", "FLIPS", "FLIRT", "FLOAT", "FLOCK", "FLOOD",
    "FLOOR", "FLOPS", "FLORA", "FLOSS", "FLOUR", "FLOUT", "FLOWN", "FLUES", "FLUFF", "FLUID",
    "FLUKE", "FLUME", "FLUNG", "FLUNK", "FLUSH", "FLUTE", "FLYER", "FOAMY", "FOCAL", "FOCUS",
    "FOGGY", "FOILS", "FOLDS", "FOLLY", "FORAY", "FORCE", "FORGE", "FORGO", "FORKS", "FORMS",
    "FORTE", "FORTH", "FORTS", "FORTY", "FORUM", "FOUND", "FOUNT", "FOXES", "FOYER", "FRAIL",
    "FRAME", "FRANC", "FRANK", "FRAUD", "FREAK", "FREED", "FREER", "FRESH", "FRIAR", "FRIED",
    "FRIES", "FRILL", "FRISK", "FRITZ", "FROCK", "FROND", "FRONT", "FROST", "FROTH", "FROWN",
    "FROZE", "FRUIT", "FUDGE", "FUELS", "FUGAL", "FULLY", "FUNDS", "FUNGI", "FUNKY", "FUNNY",
    "FUROR", "FURRY", "FUSED", "FUSES", "FUSSY", "FUTON", "FUZZY", "GAFFE", "GAILY", "GAMER",
    "GAMMA", "GAMUT", "GATED", "GATES", "GAUDY", "GAUGE", "GAUNT", "GAUZE", "GAVEL", "GAWKY",
    "GAYER", "GAYLY", "GAZER", "GAZES", "GEARS", "GECKO", "GEESE", "GENES", "GENIE", "GENRE",
    "GENTS", "GHOST", "GHOUL", "GIANT", "GIDDY", "GILLS", "GIRDS", "GIRLS", "GIRLY", "GIROS",
    "GIRTH", "GIVEN", "GIVER", "GIVES", "GIZMO", "GLADE", "GLAND", "GLARE", "GLASS", "GLAZE",
    "GLEAM", "GLEAN", "GLIDE", "GLINT", "GLOAT", "GLOBE", "GLOOM", "GLORY", "GLOSS", "GLOVE",
    "GLOWN", "GLUES", "GLUEY", "GLYPH", "GNARL", "GNASH", "GNATS", "GNOME", "GOALS", "GOATS",
    "GOFER", "GOING", "GOLDS", "GOLLY", "GONER", "GOODS", "GOODY", "GOOSE", "GORED", "GOUGE",
    "GOURD", "GRACE", "GRADE", "GRAFT", "GRAIL", "GRAIN", "GRAND", "GRANT", "GRAPE", "GRAPH",
    "GRASP", "GRASS", "GRATE", "GRAVE", "GRAVY", "GRAZE", "GREAT", "GREED", "GREEN", "GREET",
    "GRIEF", "GRILL", "GRIME", "GRIMM", "GRIND", "GRIPE", "GROAN", "GROIN", "GROOM", "GROPE",
    "GROSS", "GROUP", "GROUT", "GROVE", "GROWL", "GROWN", "GROWS", "GRUBS", "GRUEL", "GRUFF",
    "GRUNT", "GUARD", "GUESS", "GUEST", "GUIDE", "GUILD", "GUILE", "GUILT", "GUISE", "GULCH",
    "GULLS", "GULLY", "GUMBO", "GUMMY", "GURUS", "GUSTO", "GUSTS", "GUSTY", "GYPSY", "HABIT",
    "HAILS", "HAIRS", "HAIRY", "HALES", "HALLS", "HALOS", "HALTS", "HANDS", "HANDY", "HANGS",
    "HAPPY", "HARDY", "HARED", "HAREM", "HARES", "HARMS", "HARPS", "HARPY", "HARRY", "HARSH",
    "HASTE", "HASTY", "HATCH", "HATED", "HATER", "HATES", "HAULS", "HAVEN", "HAVES", "HAVOC",
    "HAWKS", "HAZEL", "HEADS", "HEALS", "HEAPS", "HEARD", "HEARS", "HEART", "HEATH", "HEATS",
    "HEAVE", "HEAVY", "HEDGE", "HEELS", "HEFTY", "HEIRS", "HEIST", "HELIX", "HELLO", "HELMS",
    "HELPS", "HENCE", "HERBS", "HERDS", "HERON", "HERTZ", "HIDES", "HIKES", "HILLS", "HILLY",
    "HILTS", "HINDS", "HINGE", "HINTS", "HIPPO", "HIPPY", "HIRED", "HIRES", "HITCH", "HIVES",
    "HOARD", "HOARY", "HOBBY", "HOGAN", "HOIST", "HOLDS", "HOLED", "HOLES", "HOLLY", "HOMED",
    "HOMER", "HOMES", "HOMEY", "HONEY", "HONKS", "HONOR", "HOODS", "HOOEY", "HOOKS", "HOOKY",
    "HOOPS", "HOOTS", "HOPED", "HOPES", "HORDE", "HORNS", "HORNY", "HORSE", "HOSTS", "HOTEL",
    "HOTLY", "HOUND", "HOURS", "HOUSE", "HOVEL", "HOVER", "HOWDY", "HOWLS", "HUBBY", "HUFFS",
    "HUFFY", "HUGES", "HULKS", "HULLS", "HUMAN", "HUMID", "HUMOR", "HUMPS", "HUMUS", "HUNCH",
    "HUNKS", "HUNTS", "HURRY", "HURTS", "HUSKY", "HUSSY", "HUTCH", "HYDRA", "HYENA", "HYMEN",
    "HYMNS", "ICHOR", "ICIER", "ICILY", "ICING", "IDEAL", "IDIOM", "IDIOT", "IDLER", "IDOLS",
    "IGLOO", "IMAGE", "IMAGO", "IMBUE", "IMPEL", "INANE", "INBOX", "INCUR", "INDEX", "INEPT",
    "INERT", "INFER", "INGOT", "INLAY", "INLET", "INNER", "INPUT", "INTER", "INTRO", "IONIC",
    "IRATE", "IRONS", "IRONY", "ISLES", "ISLET", "ISSUE", "ITCHY", "ITEMS", "IVORY", "JACKS",
    "JADES", "JADED", "JAILS", "JAMBS", "JAPAN", "JAUNT", "JAWED", "JAZZY", "JEANS", "JEEPS",
    "JEERS", "JELLY", "JERKY", "JESTS", "JETTY", "JEWEL", "JIFFY", "JOINT", "JOIST", "JOKED",
    "JOKER", "JOKES", "JOLLY", "JOLTS", "JOYED", "JUDGE", "JUICE", "JUICY", "JULEP", "JUMBO",
    "JUMPS", "JUMPY", "JUNKS", "JUNTA", "JUROR", "KABOB", "KAPPA", "KARAT", "KARMA", "KAYAK",
    "KEBAB", "KEELS", "KEENS", "KEEPS", "KEMPT", "KICKS", "KILLS", "KILOS", "KINDS", "KINGS",
    "KITES", "KNAVE", "KNEAD", "KNEED", "KNEEL", "KNEES", "KNELL", "KNELT", "KNIFE", "KNOCK",
    "KNOLL", "KNOWN", "KNOWS", "KOALA", "KRAUT", "LABEL", "LABOR", "LACED", "LACES", "LACKS",
    "LADEN", "LADLE", "LAGER", "LAIRD", "LAKES", "LAMBS", "LAMES", "LAMPS", "LANCE", "LANDS",
    "LANES", "LANKY", "LAPEL", "LAPSE", "LARCH", "LARGE", "LARVA", "LASER", "LASSO", "LASTS",
    "LATCH", "LATER", "LATEX", "LATHE", "LATIN", "LAUGH", "LAYER", "LAZED", "LEACH", "LEADS",
    "LEAFS", "LEAFY", "LEAKS", "LEAKY", "LEANS", "LEAPS", "LEAPT", "LEARN", "LEASE", "LEASH",
    "LEAST", "LEAVE", "LEDGE", "LEECH", "LEERS", "LEFTS", "LEFTY", "LEGAL", "LEGGY", "LEMON",
    "LEMUR", "LENDS", "LEPER", "LEVEL", "LEVER", "LIBEL", "LIEGE", "LIGHT", "LIKEN", "LILAC",
    "LIMBO", "LIMBS", "LIMES", "LIMIT", "LINED", "LINEN", "LINER", "LINES", "LINGO", "LINKS",
    "LIONS", "LISTS", "LIVED", "LIVER", "LIVES", "LIVID", "LLAMA", "LOADS", "LOAFS", "LOANS",
    "LOATH", "LOBES", "LOCAL", "LOCKS", "LOCUS", "LODGE", "LOFTS", "LOFTY", "LOGIC", "LOGS",
    "LOINS", "LOOKS", "LOOMS", "LOONS", "LOOPS", "LOOSE", "LOOTS", "LORDS", "LORRY", "LOSER",
    "LOSES", "LOTUS", "LOUSE", "LOUSY", "LOVED", "LOVER", "LOVES", "LOWER", "LOWLY", "LOYAL",
    "LUCID", "LUCKY", "LUMPS", "LUMPY", "LUNAR", "LUNCH", "LUNGE", "LUNGS", "LURCH", "LURED",
    "LURES", "LURID", "LURKS", "LUSTS", "LUSTY", "LYING", "LYMPH", "LYNCH", "LYRES", "MACAW",
    "MACHO", "MACRO", "MADAM", "MADLY", "MAFIA", "MAGIC", "MAGMA", "MAIDS", "MAILS", "MAIMS",
    "MAIZE", "MAJOR", "MAKER", "MAKES", "MALES", "MAMBO", "MAMMA", "MAMMY", "MANES", "MANGE",
    "MANGO", "MANIA", "MANIC", "MANLY", "MANNA", "MANOR", "MANSE", "MAPLE", "MARCH", "MARES",
    "MARGE", "MARIA", "MARKS", "MARRY", "MARSH", "MARTY", "MARVEL", "MASSE", "MATCH", "MATED",
    "MATER", "MATES", "MATTE", "MATZO", "MAUVE", "MAVEN", "MAVIS", "MAXED", "MAXES", "MAXIM",
    "MAYBE", "MAYOR", "MAZDA", "MAZES", "MEALS", "MEALY", "MEANS", "MEANT", "MEATS", "MECCA",
    "MEDAL", "MEDIA", "MEDIC", "MEETS", "MELEE", "MELON", "MELTS", "MEMOS", "MENDS", "MENUS",
    "MERCY", "MERGE", "MERIT", "MERRY", "MESSY", "METAL", "METED", "METEO", "METRO", "MEWED",
    "MEZZO", "MICRO", "MIDGE", "MIDST", "MIENS", "MIGHT", "MILDS", "MILES", "MILKY", "MILLS",
    "MIMED", "MIMES", "MIMIC", "MINCE", "MINDS", "MINED", "MINER", "MINES", "MINOR", "MINTS",
    "MINTY", "MINUS", "MIRTH", "MISER", "MISSY", "MISTS", "MISTY", "MITES", "MITRE", "MITTS",
    "MIXED", "MIXER", "MIXES", "MOANS", "MOATS", "MOCKS", "MODAL", "MODEL", "MODEM", "MODES",
    "MOIST", "MOLAR", "MOLDS", "MOLDY", "MONEY", "MONKS", "MONTH", "MOODS", "MOODY", "MOONS",
    "MOORS", "MOOSE", "MOPED", "MOPES", "MORAL", "MORAY", "MOREL", "MOTES", "MOTHS", "MOTIF",
    "MOTOR", "MOTTO", "MOULD", "MOUND", "MOUNT", "MOURN", "MOUSE", "MOUTH", "MOVED", "MOVER",
    "MOVES", "MOVIE", "MOWED", "MOWER", "MUCKS", "MUCKY", "MUCUS", "MUDDY", "MULCH", "MULES",
    "MULTI", "MUMMY", "MUMPS", "MUNCH", "MURAL", "MURKY", "MUSES", "MUSHY", "MUSIC", "MUSKY",
    "MUSTS", "MUSTY", "MUTED", "MUTES", "MYRRH", "MYTHS", "NABOB", "NAILS", "NAIVE", "NAKED",
    "NAMED", "NAMER", "NAMES", "NASAL", "NASTY", "NATAL", "NATTO", "NAVAL", "NAVEL", "NEARS",
    "NEATH", "NECKS", "NEEDS", "NEEDY", "NEIGH", "NERDS", "NERDY", "NERVE", "NERVY", "NESTS",
    "NETTY", "NEVER", "NEWER", "NEWLY", "NEWSY", "NEWTS", "NEXUS", "NICER", "NICHE", "NIECE",
    "NIGHT", "NINJA", "NINNY", "NINTH", "NOBLE", "NOBLY", "NOISE", "NOISY", "NOMAD", "NONCE",
    "NOOKS", "NOOSE", "NORMS", "NORTH", "NOSED", "NOSES", "NOTCH", "NOTED", "NOTES", "NOUNS",
    "NOVEL", "NOWAY", "NUDES", "NUDGE", "NUKED", "NUKES", "NURSE", "NUTTY", "NYLON", "NYMPH",
    "OAKEN", "OASES", "OASIS", "OATEN", "OBESE", "OBOES", "OCCUR", "OCEAN", "OCTAL", "OCTET",
    "ODDER", "ODDLY", "OFFAL", "OFFER", "OFTEN", "OGLED", "OGLES", "OGRES", "OILED", "OILER",
    "OINKS", "OKAYS", "OLDEN", "OLDER", "OLDIE", "OLIVE", "OMBRE", "OMEGA", "ONION", "ONSET",
    "OOZED", "OOZES", "OPALS", "OPENS", "OPERA", "OPINE", "OPIUM", "OPTED", "OPTIC", "ORALS",
    "ORATE", "ORBIT", "ORDER", "ORGAN", "OSIER", "OTHER", "OTTER", "OUGHT", "OUNCE", "OUSTS",
    "OUTDO", "OUTED", "OUTER", "OUTGO", "OVALS", "OVARY", "OVATE", "OVENS", "OVERS", "OVERT",
    "OWING", "OWNED", "OWNER", "OXIDE", "OZONE", "PACED", "PACER", "PACES", "PACKS", "PADDY",
    "PADRE", "PAEAN", "PAGAN", "PAGED", "PAGER", "PAGES", "PAILS", "PAINS", "PAINT", "PAIRS",
    "PALED", "PALER", "PALES", "PALMS", "PANDA", "PANED", "PANEL", "PANES", "PANGS", "PANIC",
    "PANSY", "PANTS", "PANTY", "PAPAL", "PAPER", "PAPPY", "PARAS", "PARCH", "PARDY", "PARED",
    "PAREN", "PARES", "PARIS", "PARKA", "PARKS", "PARRY", "PARSE", "PARTS", "PARTY", "PASHA",
    "PASTA", "PASTE", "PASTY", "PATCH", "PATIO", "PATSY", "PATTY", "PAUSE", "PAVED", "PAVES",
    "PAWED", "PAWLS", "PAWNS", "PAYED", "PAYEE", "PAYER", "PEACE", "PEACH", "PEAKS", "PEARL",
    "PEARS", "PEASE", "PECAN", "PEDAL", "PEEPS", "PEERS", "PEEVE", "PELTS", "PENAL", "PENCE",
    "PENIS", "PENNE", "PENNY", "PEONS", "PEEPS", "PERCH", "PERIL", "PERKS", "PERKY", "PERMS",
    "PESKY", "PESTS", "PETAL", "PETTY", "PHASE", "PHONE", "PHONY", "PHOTO", "PIANO", "PICOT",
    "PIECE", "PIERS", "PIETY", "PIGGY", "PIKES", "PILED", "PILES", "PILLS", "PILOT", "PIMPS",
    "PINCH", "PINED", "PINES", "PINKS", "PINKY", "PINTS", "PIOUS", "PIPED", "PIPER", "PIPES",
    "PIQUE", "PITCH", "PITHY", "PIVOT", "PIXEL", "PIXIE", "PIZZA", "PLACE", "PLAID", "PLAIN",
    "PLAIT", "PLANE", "PLANK", "PLANS", "PLANT", "PLATE", "PLAYS", "PLAZA", "PLEAD", "PLEAS",
    "PLEAT", "PLIED", "PLIES", "PLOTS", "PLOYS", "PLUCK", "PLUMB", "PLUME", "PLUMP", "PLUMS",
    "PLUNK", "PLUSH", "POEMS", "POETS", "POINT", "POISE", "POKED", "POKER", "POKES", "POLAR",
    "POLES", "POLKA", "POLLS", "POLLY", "PONDS", "POOLS", "POPES", "POPPY", "PORCH", "PORED",
    "PORES", "PORTS", "POSED", "POSER", "POSES", "POSIT", "POSSE", "POSTS", "POTTY", "POUCH",
    "POUND", "POURS", "POUTS", "POWER", "PRANK", "PRATE", "PRAWN", "PRAYS", "PREEN", "PREPS",
    "PRESS", "PREYS", "PRICE", "PRICK", "PRIDE", "PRIED", "PRIES", "PRIME", "PRIMO", "PRINT",
    "PRIOR", "PRISM", "PRIVY", "PRIZE", "PROBE", "PRODS", "PROMS", "PRONE", "PRONG", "PROOF",
    "PROPS", "PROSE", "PROUD", "PROVE", "PROWL", "PROXY", "PRUDE", "PRUNE", "PSALM", "PSYCH",
    "PUBIC", "PUFFS", "PUFFY", "PULLS", "PULPY", "PULSE", "PUMPS", "PUNCH", "PUPIL", "PUPPY",
    "PUREE", "PURER", "PURGE", "PURSE", "PUSHY", "PUTTY", "PYGMY", "PYLON", "QUAIL", "QUEEN",
    "QUEER", "QUELL", "QUERY", "QUEST", "QUEUE", "QUICK", "QUIET", "QUILL", "QUILT", "QUIPS",
    "QUIRE", "QUITE", "QUITS", "QUOTA", "QUOTE", "QUOTH", "RABBI", "RABID", "RACED", "RACER",
    "RACES", "RACKS", "RADAR", "RADII", "RADIO", "RAINY", "RAISE", "RAJAH", "RAKED", "RAKER",
    "RAKES", "RALLY", "RALPH", "RAMPS", "RANCH", "RANDS", "RANGE", "RAPID", "RARER", "RASPY",
    "RATED", "RATER", "RATES", "RATIO", "RAVED", "RAVEL", "RAVEN", "RAYED", "RAYON", "RAZED",
    "RAZER", "RAZES", "RAZOR", "REACH", "REACT", "READS", "READY", "REALM", "REALS", "REARM",
    "REBEL", "REBUS", "RECAP", "RECUR", "REEDY", "REFER", "REFIT", "REGAL", "REHAB", "REIGN",
    "RELAX", "RELAY", "RELIC", "REMIT", "RENAL", "RENEW", "REPAY", "REPEL", "REPLY", "RERUN",
    "RESET", "RESIN", "RESTS", "RETCH", "RETRO", "RETRY", "REUSE", "REVEL", "REVUE", "RHEME",
    "RHOSE", "RHUMB", "RHYME", "RIDER", "RIDES", "RIDGE", "RIFLE", "RIGHT", "RIGID", "RIGOR",
    "RILED", "RILES", "RINDS", "RINGS", "RINKS", "RIOTS", "RIPEN", "RIPER", "RISEN", "RISER",
    "RISES", "RISKS", "RISKY", "RITES", "RIVAL", "RIVER", "ROADS", "ROAMS", "ROAST", "ROBED",
    "ROBES", "ROBIN", "ROBOT", "ROCKS", "ROCKY", "RODEO", "ROGER", "ROGUE", "ROLES", "ROLLS",
    "ROMAN", "ROOMS", "ROOTS", "ROPED", "ROPER", "ROPES", "ROSES", "ROTOR", "ROUGE", "ROUGH",
    "ROUND", "ROUSE", "ROUTE", "ROVED", "ROVER", "ROVES", "ROWAN", "ROWDY", "ROWED", "ROWEL",
    "ROYAL", "RUBES", "RUDDY", "RUDE", "RUDER", "RUING", "RULED", "RULER", "RULES", "RUNES",
    "RUNGS", "RUNNY", "RUNTS", "RURAL", "RUSES", "SABER", "SABLE", "SABRE", "SACKS", "SADLY",
    "SAFER", "SAFES", "SAINT", "SALAD", "SALES", "SALLY", "SALON", "SALSA", "SALTS", "SALTY",
    "SALVE", "SALVO", "SANDS", "SANDY", "SANER", "SAPPY", "SARGE", "SARIS", "SATIN", "SATYR",
    "SAUCE", "SAUCY", "SAUNA", "SAUTE", "SAVED", "SAVER", "SAVES", "SAVOR", "SAVVY", "SAWED",
    "SAXES", "SAYER", "SCABS", "SCALD", "SCALE", "SCALP", "SCALY", "SCAMP", "SCANS", "SCANT",
    "SCARE", "SCARF", "SCARS", "SCARY", "SCATS", "SCENE", "SCENT", "SCION", "SCOFF", "SCOLD",
    "SCONE", "SCOOP", "SCOPE", "SCORE", "SCORN", "SCOTS", "SCOUT", "SCOWL", "SCRAM", "SCRAP",
    "SCREE", "SCREW", "SCRIP", "SCRUB", "SCUBA", "SCUDS", "SCUFF", "SEALS", "SEAMS", "SEARS",
    "SEATS", "SECTS", "SEDAN", "SEEDS", "SEEDY", "SEEKS", "SEEMS", "SEEPS", "SEERS", "SEIZE",
    "SELLS", "SEMEN", "SENDS", "SENSE", "SEOUL", "SERFS", "SERGE", "SERUM", "SERVE", "SERVO",
    "SETUP", "SEVEN", "SEVER", "SEWED", "SEWER", "SEXED", "SEXES", "SHACK", "SHADE", "SHADS",
    "SHADY", "SHAFT", "SHAGS", "SHAKE", "SHAKY", "SHALE", "SHALL", "SHALT", "SHAME", "SHAMS",
    "SHANK", "SHAPE", "SHARD", "SHARE", "SHARK", "SHARP", "SHAVE", "SHAWL", "SHEAF", "SHEAR",
    "SHEDS", "SHEEN", "SHEEP", "SHEER", "SHEET", "SHEIK", "SHELF", "SHELL", "SHIED", "SHIFT",
    "SHINE", "SHINS", "SHINY", "SHIPS", "SHIRE", "SHIRK", "SHIRT", "SHOAL", "SHOCK", "SHOED",
    "SHOES", "SHOJI", "SHONE", "SHOOK", "SHOOT", "SHOPS", "SHORE", "SHORT", "SHOTS", "SHOUT",
    "SHOVE", "SHOWN", "SHOWS", "SHOWY", "SHRED", "SHREW", "SHRUB", "SHRUG", "SHUCK", "SHUNT",
    "SHUTS", "SHYLY", "SIBYL", "SIDED", "SIDES", "SIDLE", "SIEGE", "SIEVE", "SIGHS", "SIGHT",
    "SIGMA", "SIGNS", "SILLY", "SILOS", "SILTS", "SILTY", "SILVER", "SIMON", "SINCE", "SINEW",
    "SINGE", "SINGS", "SINKS", "SIREN", "SISSY", "SITAR", "SITED", "SITES", "SIXES", "SIXTH",
    "SIXTY", "SIZED", "SIZES", "SKATE", "SKEIN", "SKEWS", "SKIDS", "SKIED", "SKIES", "SKIFF",
    "SKILL", "SKIMP", "SKIMS", "SKINS", "SKIPS", "SKIRT", "SKULK", "SKULL", "SKUNK", "SLABS",
    "SLACK", "SLAIN", "SLANG", "SLANT", "SLAPS", "SLASH", "SLATE", "SLATS", "SLAVE", "SLEDS",
    "SLEEK", "SLEEP", "SLEET", "SLEPT", "SLICE", "SLICK", "SLIDE", "SLIME", "SLIMY", "SLING",
    "SLINK", "SLIPS", "SLITS", "SLOGS", "SLOOP", "SLOPE", "SLOSH", "SLOTH", "SLOTS", "SLOWLY",
    "SLUGS", "SLUMP", "SLUMS", "SLUNG", "SLUNK", "SLURP", "SLURS", "SLUTS", "SLYLY", "SMACK",
    "SMALL", "SMART", "SMASH", "SMEAR", "SMELL", "SMELT", "SMILE", "SMIRK", "SMITE", "SMITH",
    "SMOCK", "SMOKE", "SMOKY", "SMOTE", "SNACK", "SNAIL", "SNAKE", "SNAKY", "SNAPS", "SNARE",
    "SNARL", "SNEAK", "SNEER", "SNIDE", "SNIFF", "SNIPE", "SNIPS", "SNITS", "SNOBS", "SNOOP",
    "SNORE", "SNORT", "SNOTS", "SNOUT", "SNOWS", "SNOWY", "SNUCK", "SNUFF", "SOAPY", "SOARS",
    "SOBER", "SOCKS", "SOILS", "SOLAR", "SOLDS", "SOLID", "SOLVE", "SONAR", "SONGS", "SONIC",
    "SONNY", "SOOTH", "SOOTS", "SORRY", "SORTS", "SOULS", "SOUND", "SOUPY", "SOUTH", "SOWER",
    "SPACE", "SPADE", "SPANK", "SPARE", "SPARK", "SPARS", "SPASM", "SPATE", "SPATS", "SPAWN",
    "SPAYS", "SPEAK", "SPEAR", "SPECK", "SPECS", "SPEED", "SPELL", "SPELT", "SPEND", "SPENT",
    "SPERM", "SPICE", "SPICY", "SPIED", "SPIES", "SPIKE", "SPIKY", "SPILL", "SPILT", "SPINE",
    "SPINS", "SPINY", "SPIRE", "SPITE", "SPITS", "SPLIT", "SPOIL", "SPOKE", "SPOOF", "SPOOK",
    "SPOOL", "SPOON", "SPORE", "SPORT", "SPOTS", "SPOUT", "SPRAT", "SPRAY", "SPREE", "SPRIG",
    "SPUNK", "SPURN", "SPURS", "SPURT", "SQUAB", "SQUAD", "SQUAT", "SQUID", "STABS", "STACK",
    "STAFF", "STAGE", "STAID", "STAIR", "STAKE", "STALE", "STALK", "STALL", "STAMP", "STAND",
    "STANK", "STARE", "STARK", "STARS", "START", "STASH", "STATE", "STATS", "STAVE", "STEAD",
    "STEAK", "STEAL", "STEAM", "STEED", "STEEL", "STEEP", "STEER", "STEIN", "STERN", "STICK",
    "STIFF", "STILL", "STILT", "STING", "STINK", "STINT", "STIRS", "STOKE", "STOLE", "STOMP",
    "STONE", "STOOD", "STOOL", "STOOP", "STORE", "STORK", "STORM", "STORY", "STOUT", "STOVE",
    "STRAP", "STRAW", "STRAY", "STREP", "STREW", "STRIP", "STROP", "STRUM", "STRUT", "STUBS",
    "STUCK", "STUDY", "STUFF", "STUMP", "STUNG", "STUNK", "STUNT", "STYLE", "SUAVE", "SUCKS",
    "SUCKY", "SUGAR", "SUING", "SUITE", "SUITS", "SULKY", "SULLY", "SUMAC", "SUNNY", "SUNUP",
    "SUPER", "SURER", "SURGE", "SURLY", "SUSHI", "SWAMI", "SWAMP", "SWANK", "SWANS", "SWAPS",
    "SWARM", "SWATS", "SWAYS", "SWEAR", "SWEAT", "SWEEP", "SWEET", "SWELL", "SWEPT", "SWIFT",
    "SWILL", "SWIMS", "SWINE", "SWING", "SWIRL", "SWISH", "SWOON", "SWOOP", "SWORD", "SWORE",
    "SWORN", "SWUNG", "SYRUP", "TABBY", "TABLE", "TABOO", "TACIT", "TACKS", "TACKY", "TAFFY",
    "TAILS", "TAINT", "TAKEN", "TAKER", "TAKES", "TALES", "TALKS", "TALKY", "TALLY", "TALON",
    "TAMED", "TAMER", "TAMES", "TANGO", "TANKS", "TAPED", "TAPES", "TAPIR", "TARDY", "TAROT",
    "TARTS", "TASKS", "TASTE", "TASTY", "TATTY", "TAUNT", "TAWNY", "TAXED", "TAXES", "TAXIS",
    "TEACH", "TEAMS", "TEARS", "TEARY", "TEASE", "TEATS", "TECHS", "TEENS", "TEENY", "TEETH",
    "TELEX", "TELLT", "TELLS", "TEMPO", "TEMPT", "TENDS", "TENET", "TENOR", "TENSE", "TENTH",
    "TENTS", "TEPEE", "TEPID", "TERMS", "TERRA", "TERSE", "TESTS", "TESTY", "TETRA", "TEXAS",
    "TEXTS", "THANK", "THATS", "THEFT", "THEIR", "THEME", "THERE", "THESE", "THICK", "THIEF",
    "THIGH", "THINE", "THING", "THINK", "THIRD", "THONG", "THORN", "THOSE", "THREE", "THREW",
    "THROB", "THROW", "THRUM", "THUMB", "THUMP", "THYME", "TIARA", "TIBET", "TICKS", "TIDAL",
    "TIDED", "TIDES", "TIERS", "TIGER", "TIGHT", "TILES", "TIMED", "TIMER", "TIMES", "TIMID",
    "TINES", "TINGE", "TINGS", "TINTS", "TINY", "TIPSY", "TIRED", "TIRES", "TITLE", "TOADS",
    "TOADY", "TOAST", "TODAY", "TOEFL", "TOGAS", "TOILS", "TOKEN", "TONAL", "TONED", "TONER",
    "TONES", "TONGS", "TONIC", "TOOLS", "TOOTH", "TOPAZ", "TOPIC", "TORCH", "TORSO", "TORUS",
    "TOTAL", "TOTED", "TOTEM", "TOUCH", "TOUGH", "TOURS", "TOWED", "TOWEL", "TOWER", "TOWNS",
    "TOXIC", "TOXIN", "TOYED", "TRACE", "TRACK", "TRACT", "TRADE", "TRAIL", "TRAIN", "TRAIT",
    "TRAMP", "TRAPS", "TRASH", "TRAWL", "TREAD", "TREAT", "TREES", "TREND", "TRIAD", "TRIAL",
    "TRIBE", "TRICK", "TRIED", "TRIER", "TRIES", "TRILL", "TRIMS", "TRIOS", "TRIPS", "TRITE",
    "TROLL", "TROOP", "TROPE", "TROUT", "TROVE", "TRUCE", "TRUCK", "TRUED", "TRUER", "TRUES",
    "TRUMP", "TRUNK", "TRUSS", "TRUST", "TRUTH", "TRYST", "TUBBY", "TUBER", "TUBES", "TUCKS",
    "TUFFS", "TULIP", "TULLE", "TUMOR", "TUNED", "TUNER", "TUNES", "TUNIC", "TURBO", "TURDS",
    "TURFY", "TURNS", "TUSKS", "TUTOR", "TUTUS", "TUXES", "TWAIN", "TWANG", "TWEAK", "TWEED",
    "TWEEN", "TWEET", "TWICE", "TWIGS", "TWILL", "TWINE", "TWINS", "TWIRL", "TWIST", "TWIXT",
    "TYING", "TYKES", "TYPED", "TYPES", "TYRES", "ULCER", "ULTRA", "UMBRA", "UNCLE", "UNCUT",
    "UNDER", "UNDID", "UNDUE", "UNFED", "UNFIT", "UNIFY", "UNION", "UNITE", "UNITS", "UNITY",
    "UNMET", "UNTIE", "UNTIL", "UNWED", "UNZIP", "UPPED", "UPPER", "UPSET", "URBAN", "URGED",
    "URGES", "URINE", "USAGE", "USERS", "USHER", "USING", "USUAL", "USURP", "UTILE", "UTTER",
    "VAGUE", "VALET", "VALID", "VALOR", "VALUE", "VALVE", "VAPID", "VAPOR", "VAULT", "VAUNT",
    "VEGAN", "VEILS", "VEINS", "VELDT", "VENAL", "VENDS", "VENOM", "VENTS", "VENUE", "VERBS",
    "VERGE", "VERSE", "VERVE", "VESTS", "VEXED", "VEXES", "VIALS", "VIBES", "VICAR", "VICES",
    "VIDEO", "VIEWS", "VIGIL", "VIGOR", "VILLA", "VINYL", "VIOLA", "VIPER", "VIRAL", "VIRUS",
    "VISAS", "VISIT", "VISOR", "VISTA", "VITAL", "VIVID", "VIXEN", "VOCAL", "VODKA", "VOGUE",
    "VOICE", "VOIDS", "VOLTS", "VOMIT", "VOTED", "VOTER", "VOTES", "VOUCH", "VOWED", "VOWEL",
    "WACKY", "WADER", "WAFER", "WAGED", "WAGER", "WAGES", "WAGON", "WAIFS", "WAILS", "WAIST",
    "WAITS", "WAIVE", "WAKED", "WAKEN", "WAKES", "WALKS", "WALLS", "WALTZ", "WANDS", "WANED",
    "WANES", "WANTS", "WARDS", "WARES", "WARMS", "WARNS", "WARTS", "WASHY", "WASPS", "WASTE",
    "WATCH", "WATER", "WAVER", "WAVES", "WAXED", "WAXEN", "WAXES", "WEARS", "WEARY", "WEAVE",
    "WEDGE", "WEEDS", "WEEKS", "WEIGH", "WEIRD", "WELCH", "WELDS", "WELLS", "WELSH", "WENCH",
    "WHACK", "WHALE", "WHARF", "WHEAT", "WHEEL", "WHELP", "WHERE", "WHICH", "WHIFF", "WHILE",
    "WHIMS", "WHINE", "WHIPS", "WHIRL", "WHISK", "WHITE", "WHOLE", "WHOOP", "WHORE", "WHOSE",
    "WIDEN", "WIDER", "WIDES", "WIDOW", "WIDTH", "WIELD", "WIGHT", "WILDS", "WILES", "WILLS",
    "WILLY", "WIMPS", "WIMPY", "WINCE", "WINCH", "WINDS", "WINDY", "WINED", "WINES", "WINGS",
    "WINKS", "WIPED", "WIPES", "WIRED", "WIRES", "WISER", "WISPS", "WISPY", "WITCH", "WITTY",
    "WIVES", "WOKEN", "WOMAN", "WOMEN", "WOODS", "WOODY", "WOOED", "WOOER", "WOOFS", "WOOZY",
    "WORDS", "WORDY", "WORKS", "WORLD", "WORMS", "WORMY", "WORRY", "WORSE", "WORST", "WORTH",
    "WOULD", "WOUND", "WOVEN", "WRAPS", "WRATH", "WREAK", "WRECK", "WRENS", "WREST", "WRING",
    "WRIST", "WRITE", "WRONG", "WROTE", "WRUNG", "WRYLY", "YACHT", "YANKS", "YARDS", "YARNS",
    "YAWED", "YAWLS", "YAWNS", "YEAHS", "YEARN", "YEARS", "YEAST", "YELLS", "YELPS", "YODEL",
    "YOKED", "YOKEL", "YOKES", "YOLKS", "YOUNG", "YOURS", "YOUTH", "YOWLS", "ZEBRA", "ZEROS",
    "ZESTS", "ZESTY", "ZONED", "ZONES", "ZONKS"
]

# Possible daily answer words (subset of valid guesses - common challenging words)
DAILY_ANSWERS = [
    "ABOUT", "ABOVE", "ABUSE", "ACTOR", "ACUTE", "ADMIT", "ADOPT", "ADULT", "AFTER", "AGAIN",
    "AGENT", "AGREE", "AHEAD", "ALARM", "ALBUM", "ALERT", "ALIEN", "ALIGN", "ALIKE", "ALIVE",
    # Additional common words for daily challenges
    "ABACK", "ABASE", "ABATE", "ABBEY", "ABBOT", "ABHOR", "ABIDE", "ABODE", "ABORT", "ABOUND",
    "ABUSE", "ABYSS", "ACORN", "ACRID", "ACTED", "ACTIN", "ACTOR", "ACUTE", "ADAGE", "ADAPT",
    "ADEPT", "ADMIN", "ADMIT", "ADOBE", "ADOPT", "ADORE", "ADORN", "ADULT", "AFFIX", "AFIRE",
    "AFOOT", "AFORE", "AFRESH", "AGATE", "AGAVE", "AGENT", "AGILE", "AGING", "AGLOW", "AGONY",
    "AGREE", "AHEAD", "AIDER", "AIDES", "AILED", "AIMED", "AIRED", "AISLE", "ALARM", "ALBUM",
    "ALERT", "ALGAE", "ALIBI", "ALIEN", "ALIGN", "ALIKE", "ALIVE", "ALLAY", "ALLEY", "ALLOT",
    "ALLOW", "ALLOY", "ALOFT", "ALONE", "ALONG", "ALOOF", "ALOUD", "ALPHA", "ALTAR", "ALTER",
    "AMASS", "AMBER", "AMBLE", "AMEND", "AMISS", "AMITY", "AMONG", "AMPLE", "AMPLY", "AMUSE",
    "ANGEL", "ANGER", "ANGLE", "ANGRY", "ANGST", "ANIME", "ANKLE", "ANNEX", "ANNOY", "ANNUL",
    "ANODE", "ANTIC", "ANVIL", "AORTA", "APART", "APHID", "APING", "APNEA", "APPLE", "APPLY",
    "ARENA", "ARGUE", "ARISE", "ARMED", "ARMOR", "AROMA", "AROSE", "ARRAY", "ARROW", "ARSON",
    "ARTSY", "ASCOT", "ASHEN", "ASIDE", "ASKEW", "ASSAY", "ASSET", "ATOLL", "ATONE", "ATTIC",
    "AUDIO", "AUDIT", "AUGUR", "AUNTY", "AVAIL", "AVERT", "AVIAN", "AVOID", "AWAIT", "AWAKE",
    "AWARD", "AWARE", "AWASH", "AWFUL", "AWOKE", "AXIAL", "AXIOM", "AXLES", "AZURE", "BACON",
    "BADGE", "BADLY", "BAGEL", "BAILY", "BAKER", "BALER", "BALMY", "BANAL", "BANJO", "BARGE",
    "BARON", "BASAL", "BASIC", "BASIL", "BASIN", "BASIS", "BASTE", "BATCH", "BATHE", "BATON",
    "BATTY", "BAWLS", "BEACH", "BEADS", "BEADY", "BEAMS", "BEAMY", "BEARS", "BEAST", "BEATS",
    "BEGAN", "BEGAT", "BEGET", "BEGIN", "BEGUN", "BEING", "BELCH", "BELIE", "BELLE", "BELLS",
    "BERET", "BERTH", "BESET", "BESTS", "BETEL", "BEVEL", "BEZEL", "BIBLE", "BICEP", "BIDDY",
    "BIGOT", "BILGE", "BILLY", "BINGE", "BINGO", "BIOME", "BIRCH", "BIRDS", "BIRTH", "BISON",
    "BITTY", "BLACK", "BLADE", "BLAME", "BLAND", "BLANK", "BLARE", "BLAST", "BLAZE", "BLEAK",
    "BLEAT", "BLEED", "BLEEP", "BLEND", "BLESS", "BLIMP", "BLIND", "BLINK", "BLISS", "BLITZ",
    "BLOAT", "BLOCK", "BLOKE", "BLOND", "BLOOD", "BLOOM", "BLOWN", "BLUES", "BLUFF", "BLUNT",
    "BLURB", "BLURT", "BLUSH", "BOARD", "BOAST", "BOATS", "BOBBY", "BODES", "BOILS", "BOING",
    "BOLTS", "BONDS", "BONED", "BONER", "BONGS", "BONUS", "BOOBY", "BOOST", "BOOTH", "BOOTS",
    "BOOTY", "BOOZE", "BOOZY", "BORAX", "BORNE", "BOSOM", "BOSON", "BOTCH", "BOUGH", "BOULE",
    "BOUND", "BOWEL", "BOWER", "BOXED", "BOXER", "BOXES", "BRACE", "BRAID", "BRAIN", "BRAKE",
    "BRAND", "BRASH", "BRASS", "BRAVE", "BRAVO", "BRAWL", "BRAWN", "BRAWN", "BRAYS", "BRAZE",
    "BREAD", "BREAK", "BREVE", "BRIBE", "BRICK", "BRIDE", "BRIEF", "BRINE", "BRING", "BRINK",
    "BRINY", "BRISK", "BROAD", "BROIL", "BROKE", "BROOD", "BROOK", "BROOM", "BROTH", "BROWN",
    "BRUNT", "BRUSH", "BRUTE", "BUDDY", "BUDGE", "BUGGY", "BUGLE", "BUILD", "BUILT", "BULBS",
    "BULGE", "BULKY", "BULLY", "BUMPS", "BUMPY", "BUNCH", "BUNNY", "BURNT", "BURST", "BUSED",
    "BUSHY", "BUTCH", "BUTTE", "BUXOM", "BUYER", "BYLAW", "CABAL", "CABBY", "CABIN", "CABLE",
    "CACAO", "CACHE", "CACTI", "CADDY", "CADET", "CAGEY", "CAIRN", "CAKES", "CALFS", "CALLS",
    "CALMS", "CAMEL", "CAMEO", "CANAL", "CANDY", "CANED", "CANES", "CANNY", "CANOE", "CANON",
    "CAPER", "CAPES", "CARAT", "CARGO", "CAROL", "CARRY", "CARVE", "CASED", "CASES", "CASTE",
    "CASTS", "CATCH", "CATER", "CATTY", "CAULK", "CAUSE", "CAVED", "CAVES", "CEASE", "CEDAR",
    "CEDED", "CELEB", "CELLS", "CENTS", "CHAFE", "CHAFF", "CHAIN", "CHAIR", "CHAIR", "CHALK",
    "CHAMP", "CHANT", "CHAOS", "CHARM", "CHART", "CHASE", "CHASM", "CHEAP", "CHEAT", "CHECK",
    "CHEEK", "CHEER", "CHEFS", "CHESS", "CHEST", "CHICK", "CHIEF", "CHILD", "CHILI", "CHILL",
    "CHIME", "CHINA", "CHIRP", "CHOCK", "CHOIR", "CHOKE", "CHORD", "CHORE", "CHOSE", "CHUCK",
    "CHUMP", "CHUNK", "CHURN", "CHUTE", "CIDER", "CIGAR", "CINCH", "CIRCA", "CITED", "CITES",
    "CIVET", "CIVIC", "CIVIL", "CLACK", "CLAIM", "CLAMP", "CLANG", "CLANK", "CLASH", "CLASP",
    "CLASS",
    "CLEAN", "CLEAR", "CLEAT", "CLEFS", "CLEFT", "CLERK", "CLICK", "CLIFF", "CLIMB", "CLING",
    "CLINK", "CLOAK", "CLOCK", "CLONE", "CLOSE", "CLOTH", "CLOUD", "CLOUT", "CLOVE", "CLOWN",
    "CLUBS", "CLUCK", "CLUED", "CLUES", "CLUMP", "CLUNG", "COACH", "COALS", "COAST", "COBRA",
    "COCOA", "CODED", "CODES", "COILS", "COINS", "COLDS", "COLON", "COLTS", "COMBO", "COMES",
    "COMET", "COMFY", "COMIC", "COMMA", "CONCH", "CONDO", "CONIC", "COPSE", "CORAL", "CORER",
    "CORNY", "COSTS", "COUCH", "COUGH", "COULD",
    "COUNT", "COUPE", "COURT", "COVEN", "COVER", "COVET", "COVEY", "COWER", "COYLY", "CRABS",
    "CRACK", "CRAFT", "CRAMP", "CRANE", "CRANK", "CRASH", "CRASS", "CRATE", "CRAVE", "CRAWL",
    "CRAZE", "CRAZY", "CREAK", "CREAM", "CREDO", "CREED", "CREEK", "CREEP", "CREME", "CREPE",
    "CREPT", "CRESS", "CREST", "CRICK", "CRIED", "CRIES", "CRIME", "CRIMP", "CRISP", "CROAK",
    "CROCK", "CRONE", "CRONY", "CROOK", "CROSS", "CROUP", "CROWD",
    "CROWN", "CRUDE", "CRUEL", "CRUMB", "CRUMP", "CRUSH", "CRUST", "CRYPT", "CUBIC", "CUMIN",
    "CUPID", "CURED", "CURES", "CURIO", "CURLS", "CURLY", "CURRY", "CURSE", "CURVE", "CURVY",
    "CUTIE", "CYCLE", "CYNIC", "DABBA", "DAILY", "DAIRY", "DAISY", "DALES", "DAMES", "DAMNS",
    "DANCE", "DANDY", "DATED", "DAUNT", "DAVIT", "DAWNS", "DEALS", "DEALT", "DEATH", "DEBAR",
    "DEBIT", "DEBUG", "DEBUT", "DECAL", "DECAY", "DECOR", "DECOY", "DECRY", "DEFER", "DEIGN",
    "DEITY", "DELAY", "DELTA", "DELVE", "DEMON", "DEMOS", "DENIM", "DENSE", "DEPOT", "DEPTH",
    "DERBY", "DETER", "DETOX", "DEUCE", "DEVIL", "DIARY", "DICED", "DICES", "DIGIT", "DILLY",
    "DIMLY", "DINER", "DINGO", "DINGY", "DIODE", "DIRGE", "DIRTY", "DISCO", "DITCH", "DITTO",
    "DITTY", "DIVER", "DIZZY", "DODGE", "DODGY", "DOGGY", "DOGMA", "DOING", "DOLLY", "DONOR",
    "DONUT", "DOPEY", "DOUBT", "DOUSE", "DOVER", "DOWEL", "DOWNY", "DOZEN", "DRAFT", "DRAGS",
    "DRAIN", "DRAKE", "DRAMA", "DRANK", "DRAPE", "DRAWL", "DRAWN", "DRAWS", "DREAD", "DREAM",
    "DRESS", "DRIED", "DRIER", "DRIES", "DRIFT", "DRILL", "DRINK", "DRIVE", "DROIT", "DROLL",
    "DRONE", "DROOL", "DROPS", "DROSS", "DROVE", "DROWN", "DRUID", "DRUMS", "DRUNK", "DRYER",
    "DRYLY", "DUCHY", "DULLS", "DUMMY", "DUMPS", "DUMPY", "DUNCE", "DUSKY", "DUSTY", "DUTCH",
    "DUVET", "DWARF", "DWELL", "DWELT", "DYING", "EAGER", "EAGLE", "EARLY", "EARTH", "EIGHT",
    "ELITE", "EMPTY", "ENEMY", "ENJOY", "ENTER", "ENTRY", "EQUAL", "ERROR", "EVENT", "EVERY",
    "EXACT", "EXIST", "EXTRA", "EASED", "EASEL", "EASES", "EATEN", "EATER", "EAVES", "EBBED",
    "EBONY", "EDEMA", "EDGED", "EDGES", "EDICT", "EDIFY", "EERIE", "EGGED", "EGRET", "EIDER",
    "EJECT", "EKING", "ELATE", "ELBOW", "ELDER", "ELECT", "ELEGY", "ELFIN", "ELIDE", "ELOPE",
    "ELUDE", "EMAIL", "EMBED", "EMBER", "EMCEE", "ENACT", "ENDED", "ENDOW", "ENEMA", "ENNUI",
    "ENSUE", "ENVOY", "EPOCH", "EPOXY", "EQUIP", "ERASE", "ERECT", "ERODE", "ERUPT", "ESSAY",
    "ESTER", "ETHER", "ETHIC", "ETHOS", "ETUDE", "EVADE", "EVICT", "EVOKE", "EXALT", "EXCEL",
    "EXERT", "EXILE", "EXITS", "EXPAT", "EXPEL", "EXTOL", "FAITH", "FALSE", "FAULT", "FIBER", "FIELD", "FIFTH", "FIFTY",
    "FIGHT", "FINAL", "FIRST", "FIXED", "FLASH", "FLEET", "FLOOR", "FLUID", "FOCUS", "FORCE",
    "FORTH", "FORTY", "FORUM", "FOUND", "FRAME", "FRANK", "FRAUD", "FRESH", "FRONT", "FRUIT",
    "FULLY", "FUNNY", "GABBY", "GABLE", "GAFFE", "GAILY", "GAMER", "GAMMA", "GAMUT", "GATED",
    "GATES", "GAUDY", "GAUGE", "GAUNT", "GAUZE", "GAVEL", "GAWKY", "GAYER", "GAYLY", "GAZER",
    "GAZES", "GEARS", "GECKO", "GEESE", "GENES", "GENIE", "GENRE", "GENTS", "GHOST", "GHOUL",
    "GIANT", "GIDDY", "GILLS", "GIRDS", "GIRLS", "GIRLY", "GIROS", "GIRTH", "GIVEN", "GIVER",
    "GIVES", "GIZMO", "GLADE", "GLAND", "GLARE", "GLASS", "GLAZE", "GLEAM", "GLEAN", "GLIDE",
    "GLINT", "GLOAT", "GLOBE", "GLOOM", "GLORY", "GLOSS", "GLOVE", "GLOWN", "GLUES", "GLUEY",
    "GLYPH", "GNARL", "GNASH", "GNATS", "GNOME", "GOALS", "GOATS", "GOFER", "GOING", "GOLDS",
    "GOLLY", "GONER", "GOODS", "GOODY", "GOOSE", "GORED", "GOUGE", "GOURD", "GRACE", "GRADE",
    "GRAFT", "GRAIL", "GRAIN", "GRAND",
    "GRANT", "GRAPE", "GRAPH", "GRASP", "GRASS", "GRATE", "GRAVE", "GRAVY", "GRAZE", "GREAT",
    "GREED", "GREEN", "GREET", "GRIEF", "GRILL", "GRIME", "GRIMM", "GRIND", "GRIPE", "GROAN",
    "GROIN", "GROOM", "GROPE", "GROSS", "GROUP", "GROUT", "GROVE", "GROWL", "GROWN", "GROWS",
    "GRUBS", "GRUEL", "GRUFF", "GRUNT", "GUARD", "GUESS", "GUEST", "GUIDE", "GUILD", "GUILE",
    "GUILT", "GUISE", "GULCH", "GULLS", "GULLY", "GUMBO", "GUMMY", "GURUS", "GUSTO", "GUSTS",
    "GUSTY", "GYPSY", "HABIT", "HAILS", "HAIRS", "HAIRY", "HALES", "HALLS", "HALOS", "HALTS",
    "HANDS", "HANDY", "HANGS", "HAPPY", "HARDY", "HARED", "HAREM", "HARES", "HARMS", "HARPS",
    "HARPY", "HARSH", "HASTE", "HASTY", "HATCH", "HATED", "HATER", "HATES", "HAULS", "HAVEN",
    "HAVES", "HAVOC", "HAWKS", "HAZEL", "HEADS", "HEALS", "HEAPS", "HEARD", "HEARS", "HEART",
    "HEATH", "HEATS", "HEAVE", "HEAVY", "HEDGE", "HEELS", "HEFTY", "HEIRS", "HEIST", "HELIX",
    "HELLO", "HELMS", "HELPS", "HENCE", "HERBS", "HERDS", "HERON", "HERTZ", "HIDES", "HIKES",
    "HILLS", "HILLY", "HILTS", "HINDS", "HINGE", "HINTS", "HIPPO", "HIPPY", "HIRED", "HIRES",
    "HITCH", "HIVES", "HOARD", "HOARY", "HOBBY", "HOGAN", "HOIST", "HOLDS", "HOLED", "HOLES",
    "HOLLY", "HOMED", "HOMER", "HOMES", "HOMEY", "HONEY", "HONKS", "HONOR", "HOODS", "HOOEY",
    "HOOKS", "HOOKY", "HOOPS", "HOOTS", "HOPED", "HOPES", "HORDE", "HORNS", "HORNY", "HORSE",
    "HOSTS", "HOTEL",
    "HOUSE", "HOVEL", "HOVER", "HOWDY", "HOWLS", "HUBBY", "HUFFS", "HUFFY", "HUGES", "HULKS",
    "HULLS", "HUMAN", "HUMID", "HUMOR", "HUMPS", "HUMUS", "HUNCH", "HUNKS", "HUNTS", "HURRY",
    "HURTS", "HUSKY", "HUSSY", "HUTCH", "HYDRA", "HYENA", "HYMEN", "HYMNS", "ICHOR", "ICIER",
    "ICILY", "ICING", "IDEAL", "IDIOM", "IDIOT", "IDLER", "IDOLS", "IGLOO", "IMAGE", "IMAGO",
    "IMBUE", "IMPEL", "INANE", "INBOX", "INCUR", "INDEX", "INEPT", "INERT", "INFER", "INGOT",
    "INLAY", "INLET", "INNER", "INPUT", "INTER", "INTRO", "IONIC", "IRATE", "IRONS", "IRONY",
    "ISLES", "ISLET", "ISSUE", "ITCHY", "ITEMS", "IVORY", "JACKS", "JADES", "JADED", "JAILS",
    "JAMBS", "JAPAN", "JAUNT", "JAWED", "JAZZY", "JEANS", "JEEPS", "JEERS", "JELLY", "JERKY",
    "JESTS", "JETTY", "JEWEL", "JIFFY", "JOINT", "JOIST", "JOKED", "JOKER", "JOKES", "JOLLY",
    "JOLTS", "JOYED", "JUDGE", "JUICE", "JUICY", "JULEP", "JUMBO", "JUMPS", "JUMPY", "JUNKS",
    "JUNTA", "JUROR", "KABOB", "KAPPA", "KARAT", "KARMA", "KAYAK", "KEBAB", "KEELS", "KEENS",
    "KEEPS", "KEMPT", "KICKS", "KILLS", "KILOS", "KINDS", "KINGS", "KITES", "KNAVE", "KNEAD",
    "KNEED", "KNEEL", "KNEES", "KNELL", "KNELT", "KNIFE", "KNOCK", "KNOLL", "KNOWN", "KNOWS",
    "KOALA", "KRAUT", "LABEL", "LABOR", "LACED", "LACES", "LACKS", "LADEN", "LADLE", "LAGER",
    "LAIRD", "LAKES", "LAMBS", "LAMES", "LAMPS", "LANCE", "LANDS", "LANES", "LANKY", "LAPEL",
    "LAPSE", "LARCH", "LARGE", "LARVA", "LASER", "LASSO", "LASTS", "LATCH", "LATER", "LATEX",
    "LATHE", "LATIN", "LAUGH", "LAYER", "LAZED", "LEACH", "LEADS", "LEAFS", "LEAFY", "LEAKS",
    "LEAKY", "LEANS", "LEAPS", "LEAPT", "LEARN", "LEASE", "LEASH", "LEAST", "LEAVE", "LEDGE",
    "LEECH", "LEERS", "LEFTS", "LEFTY", "LEGAL", "LEGGY", "LEMON", "LEMUR", "LENDS", "LEPER",
    "LEVEL", "LEVER", "LIBEL", "LIEGE", "LIGHT", "LIKEN", "LILAC", "LIMBO", "LIMBS", "LIMES",
    "LIMIT", "LINED", "LINEN", "LINER", "LINES", "LINGO", "LINKS", "LIONS", "LISTS", "LIVED",
    "LIVER", "LIVES", "LIVID", "LLAMA", "LOADS", "LOAFS", "LOANS", "LOATH", "LOBES", "LOCAL",
    "LOCKS", "LOCUS", "LODGE", "LOFTS", "LOFTY", "LOGIC", "LOGS", "LOINS", "LOOKS", "LOOMS",
    "LOONS", "LOOPS", "LOOSE", "LOOTS", "LORDS", "LORRY", "LOSER", "LOSES", "LOTUS", "LOUSE",
    "LOUSY", "LOVED", "LOVER", "LOVES", "LOWER", "LOWLY", "LOYAL", "LUCID", "LUCKY", "LUMPS",
    "LUMPY", "LUNAR", "LUNCH", "LUNGE", "LUNGS", "LURCH", "LURED", "LURES", "LURID", "LURKS",
    "LUSTS", "LUSTY", "LYING", "LYMPH", "LYNCH", "LYRES", "MACAW", "MACHO", "MACRO", "MADAM",
    "MADLY", "MAFIA", "MAGIC", "MAGMA", "MAIDS", "MAILS", "MAIMS", "MAIZE", "MAJOR", "MAKER",
    "MAKES", "MALES", "MAMBO", "MAMMA", "MAMMY", "MANES", "MANGE", "MANGO", "MANIA", "MANIC",
    "MANLY", "MANNA", "MANOR", "MANSE", "MAPLE", "MARCH", "MARES", "MARGE", "MARIA", "MARKS",
    "MARRY", "MARSH", "MARTY", "MARVEL", "MASSE", "MATCH", "MATED", "MATER", "MATES", "MATTE",
    "MATZO", "MAUVE", "MAVEN", "MAVIS", "MAXED", "MAXES", "MAXIM", "MAYBE", "MAYOR", "MAZDA",
    "MAZES", "MEALS", "MEALY", "MEANS", "MEANT", "MEATS", "MECCA", "MEDAL", "MEDIA", "MEDIC",
    "MEETS", "MELEE", "MELON", "MELTS", "MEMOS", "MENDS", "MENUS", "MERCY", "MERGE", "MERIT",
    "MERRY", "MESSY", "METAL", "METED", "METEO", "METRO", "MEWED", "MEZZO", "MICRO", "MIDGE",
    "MIDST", "MIENS", "MIGHT", "MILDS", "MILES", "MILKY", "MILLS", "MIMED", "MIMES", "MIMIC",
    "MINCE", "MINDS", "MINED", "MINER", "MINES", "MINOR", "MINTS", "MINTY", "MINUS", "MIRTH",
    "MISER", "MISSY", "MISTS", "MISTY", "MITES", "MITRE", "MITTS", "MIXED", "MIXER", "MIXES",
    "MOANS", "MOATS", "MOCKS", "MODAL", "MODEL", "MODEM", "MODES", "MOIST", "MOLAR", "MOLDS",
    "MOLDY", "MONEY", "MONKS", "MONTH", "MOODS", "MOODY", "MOONS", "MOORS", "MOOSE", "MOPED",
    "MOPES", "MORAL", "MORAY", "MOREL", "MOTES", "MOTHS", "MOTIF", "MOTOR", "MOTTO", "MOULD",
    "MOUND", "MOUNT", "MOURN", "MOUSE", "MOUTH",
    "MOVED", "MOVER", "MOVES", "MOVIE", "MOWED", "MOWER", "MUCKS", "MUCKY", "MUCUS", "MUDDY",
    "MULCH", "MULES", "MULTI", "MUMMY", "MUMPS", "MUNCH", "MURAL", "MURKY", "MUSES", "MUSHY",
    "MUSIC", "MUSKY", "MUSTS", "MUSTY", "MUTED", "MUTES", "MYRRH", "MYTHS", "NABOB", "NAILS",
    "NAIVE", "NAKED", "NAMED", "NAMER", "NAMES", "NASAL", "NASTY", "NATAL", "NATTO", "NAVAL",
    "NAVEL", "NEARS", "NEATH", "NECKS", "NEEDS", "NEEDY", "NEIGH", "NERDS", "NERDY", "NERVE",
    "NERVY", "NESTS", "NETTY", "NEVER", "NEWER", "NEWLY", "NEWSY", "NEWTS", "NEXUS", "NICER",
    "NICHE", "NIECE", "NIGHT", "NINJA", "NINNY", "NINTH", "NOBLE", "NOBLY", "NOISE", "NOISY",
    "NOMAD", "NONCE", "NOOKS", "NOOSE", "NORMS", "NORTH", "NOSED", "NOSES", "NOTCH", "NOTED",
    "NOTES", "NOUNS", "NOVEL", "NOWAY", "NUDES", "NUDGE", "NUKED", "NUKES", "NURSE", "NUTTY",
    "NYLON", "NYMPH", "OAKEN", "OASES", "OASIS", "OATEN", "OBESE", "OBOES", "OCCUR", "OCEAN",
    "OCTAL", "OCTET", "ODDER", "ODDLY", "OFFAL", "OFFER", "OFTEN", "OGLED", "OGLES", "OGRES",
    "OILED", "OILER", "OINKS", "OKAYS", "OLDEN", "OLDER", "OLDIE", "OLIVE", "OMBRE", "OMEGA",
    "ONION", "ONSET", "OOZED", "OOZES", "OPALS", "OPENS", "OPERA", "OPINE", "OPIUM", "OPTED",
    "OPTIC", "ORALS", "ORATE", "ORBIT", "ORDER", "ORGAN", "OSIER", "OTHER", "OTTER", "OUGHT",
    "OUNCE", "OUSTS", "OUTDO", "OUTED", "OUTER", "OUTGO", "OVALS", "OVARY", "OVATE", "OVENS",
    "OVERS", "OVERT", "OWING", "OWNED", "OWNER", "OXIDE", "OZONE", "PACED", "PACER", "PACES",
    "PACKS", "PADDY", "PADRE", "PAEAN", "PAGAN", "PAGED", "PAGER", "PAGES", "PAILS", "PAINS",
    "PAINT", "PAIRS", "PALED", "PALER", "PALES", "PALMS", "PANDA", "PANED", "PANEL", "PANES",
    "PANGS", "PANIC", "PANSY", "PANTS", "PANTY", "PAPAL", "PAPER", "PAPPY", "PARAS", "PARCH",
    "PARDY", "PARED", "PAREN", "PARES", "PARIS", "PARKA", "PARKS", "PARRY", "PARSE", "PARTS",
    "PARTY", "PASHA", "PASTA", "PASTE", "PASTY", "PATCH", "PATIO", "PATSY", "PATTY", "PAUSE",
    "PAVED", "PAVES", "PAWED", "PAWLS", "PAWNS", "PAYED", "PAYEE", "PAYER", "PEACE", "PEACH",
    "PEAKS", "PEARL", "PEARS", "PEASE", "PECAN", "PEDAL", "PEEPS", "PEERS", "PEEVE", "PELTS",
    "PENAL", "PENCE", "PENIS", "PENNE", "PENNY", "PEONS", "PEEPS", "PERCH", "PERIL", "PERKS",
    "PERKY", "PERMS", "PESKY", "PESTS", "PETAL", "PETTY", "PHASE", "PHONE", "PHONY", "PHOTO",
    "PIANO", "PICOT", "PIECE", "PIERS", "PIETY", "PIGGY", "PIKES", "PILED", "PILES", "PILLS",
    "PILOT", "PIMPS", "PINCH", "PINED", "PINES", "PINKS", "PINKY", "PINTS", "PIOUS", "PIPED",
    "PIPER", "PIPES", "PIQUE", "PITCH", "PITHY", "PIVOT", "PIXEL", "PIXIE", "PIZZA", "PLACE",
    "PLAID", "PLAIN", "PLAIT", "PLANE", "PLANK", "PLANS", "PLANT", "PLATE", "PLAYS", "PLAZA",
    "PLEAD", "PLEAS", "PLEAT", "PLIED", "PLIES", "PLOTS", "PLOYS", "PLUCK", "PLUMB", "PLUME",
    "PLUMP", "PLUMS", "PLUNK", "PLUSH", "POEMS", "POETS", "POINT", "POISE", "POKED", "POKER",
    "POKES", "POLAR", "POLES", "POLKA", "POLLS", "POLLY", "PONDS", "POOLS", "POPES", "POPPY",
    "PORCH", "PORED", "PORES", "PORTS", "POSED", "POSER", "POSES", "POSIT", "POSSE", "POSTS",
    "POTTY", "POUCH", "POUND", "POURS", "POUTS", "POWER", "PRANK", "PRATE", "PRAWN", "PRAYS",
    "PREEN", "PREPS", "PRESS", "PREYS", "PRICE", "PRICK", "PRIDE", "PRIED", "PRIES", "PRIME",
    "PRIMO", "PRINT", "PRIOR", "PRIVY", "PRIZE", "PROBE", "PRODS", "PROMS", "PRONE", "PRONG",
    "PROOF", "PROPS", "PROSE", "PROUD", "PROVE", "PROWL", "PROXY", "PRUDE", "PRUNE", "PSALM",
    "PSYCH", "PUBIC", "PUFFS", "PUFFY", "PULLS", "PULPY", "PULSE", "PUMPS", "PUNCH", "PUPIL",
    "PUPPY", "PUREE", "PURER", "PURGE", "PURSE", "PUSHY", "PUTTY", "PYGMY", "PYLON", "QUAIL",
    "QUEEN", "QUEER", "QUELL", "QUERY", "QUEST", "QUEUE", "QUICK", "QUIET", "QUILL", "QUILT",
    "QUIPS", "QUIRE", "QUITE", "QUOTA", "QUOTE", "QUOTH", "RABBI", "RABID", "RACED", "RACER",
    "RACES", "RACKS", "RADAR", "RADII", "RADIO", "RAINY", "RAISE", "RAJAH", "RAKED", "RAKER",
    "RAKES", "RALLY", "RALPH", "RAMPS", "RANCH", "RANDS", "RANGE", "RAPID", "RARER", "RASPY",
    "RATED", "RATER", "RATES", "RATIO", "RAVED", "RAVEL", "RAVEN", "RAYED", "RAYON", "RAZED",
    "RAZER", "RAZES", "RAZOR", "REACH", "REACT", "READS", "READY", "REALM", "REALS", "REARM",
    "REBEL", "REBUS", "RECAP", "RECUR", "REEDY", "REFER", "REFIT", "REGAL", "REHAB", "REIGN",
    "RELAX", "RELAY", "RELIC", "REMIT", "RENAL", "RENEW", "REPAY", "REPEL", "REPLY", "RERUN",
    "RESET", "RESIN", "RESTS", "RETCH", "RETRO", "RETRY", "REUSE", "REVEL", "REVUE", "RHEME",
    "RHOSE", "RHUMB", "RHYME", "RIDER", "RIDES", "RIDGE", "RIFLE", "RIGHT", "RIGID", "RILED",
    "RILES", "RINDS", "RINGS", "RINKS", "RIOTS", "RIPEN", "RIPER", "RISEN", "RISER", "RISES",
    "RISKS", "RISKY", "RITES", "RIVAL", "RIVER", "ROADS", "ROAMS", "ROAST", "ROBED", "ROBES",
    "ROBIN", "ROBOT", "ROCKS", "ROCKY", "RODEO", "ROGER", "ROGUE", "ROLES", "ROLLS", "ROMAN",
    "ROOMS", "ROOTS", "ROPED", "ROPER", "ROPES", "ROSES", "ROTOR", "ROUGE", "ROUGH", "ROUND",
    "ROUTE", "ROVED", "ROVER", "ROVES", "ROWAN", "ROWDY", "ROWED", "ROWEL", "ROYAL", "RUBES",
    "RUDDY", "RUDE", "RUDER", "RUING", "RULED", "RULER", "RULES", "RUNES", "RUNGS", "RUNNY",
    "RUNTS", "RURAL", "RUSES", "SABER", "SABLE", "SABRE", "SACKS", "SADLY", "SAFER", "SAFES",
    "SAINT", "SALAD", "SALES", "SALLY", "SALON", "SALSA", "SALTS", "SALTY", "SALVE", "SALVO",
    "SANDS", "SANDY", "SANER", "SAPPY", "SARGE", "SARIS", "SATIN", "SATYR", "SAUCE", "SAUCY",
    "SAUNA", "SAUTE", "SAVED", "SAVER", "SAVES", "SAVOR", "SAVVY", "SAWED", "SAXES", "SAYER",
    "SCABS", "SCALD", "SCALE", "SCALP", "SCALY", "SCAMP", "SCANS", "SCANT", "SCARE", "SCARF",
    "SCARS", "SCARY", "SCATS", "SCENE", "SCENT", "SCION", "SCOFF", "SCOLD", "SCONE", "SCOOP",
    "SCOPE", "SCORE", "SCORN", "SCOTS", "SCOUT", "SCOWL", "SCRAM", "SCRAP", "SCREE", "SCREW",
    "SCRIP", "SCRUB", "SCUBA", "SCUDS", "SCUFF", "SEALS", "SEAMS", "SEARS", "SEATS", "SECTS",
    "SEDAN", "SEEDS", "SEEDY", "SEEKS", "SEEMS", "SEEPS", "SEERS", "SEIZE", "SELLS", "SEMEN",
    "SENDS", "SENSE", "SEOUL", "SERFS", "SERGE", "SERUM", "SERVE", "SERVO", "SETUP", "SEVEN",
    "SEVER", "SEWED", "SEWER", "SEXED", "SEXES", "SHACK", "SHADE", "SHADS", "SHADY", "SHAFT",
    "SHAGS", "SHAKE", "SHAKY", "SHALE", "SHALL", "SHALT", "SHAME", "SHAMS", "SHANK", "SHAPE",
    "SHARD", "SHARE", "SHARK", "SHARP", "SHAVE", "SHAWL", "SHEAF", "SHEAR", "SHEDS", "SHEEN",
    "SHEEP", "SHEER", "SHEET", "SHEIK", "SHELF", "SHELL", "SHIED", "SHIFT", "SHINE", "SHINS",
    "SHINY", "SHIPS", "SHIRE", "SHIRK", "SHIRT", "SHOAL", "SHOCK", "SHOED", "SHOES", "SHOJI",
    "SHONE", "SHOOK", "SHOOT", "SHOPS", "SHORE", "SHORT", "SHOTS", "SHOUT", "SHOVE", "SHOWN",
    "SHOWS", "SHOWY", "SHRED", "SHREW", "SHRUB", "SHRUG", "SHUCK", "SHUNT", "SHUTS", "SHYLY",
    "SIBYL", "SIDED", "SIDES", "SIDLE", "SIEGE", "SIEVE", "SIGHS", "SIGHT", "SIGMA", "SIGNS",
    "SILLY", "SILOS", "SILTS", "SILTY", "SILVER", "SIMON", "SINCE", "SINEW", "SINGE", "SINGS",
    "SINKS", "SIREN", "SISSY", "SITAR", "SITED", "SITES", "SIXES", "SIXTH", "SIXTY", "SIZED",
    "SIZES", "SKATE", "SKEIN", "SKEWS", "SKIDS", "SKIED", "SKIES", "SKIFF", "SKILL", "SKIMP",
    "SKIMS", "SKINS", "SKIPS", "SKIRT", "SKULK", "SKULL", "SKUNK", "SLABS", "SLACK", "SLAIN",
    "SLANG", "SLANT", "SLAPS", "SLASH", "SLATE", "SLATS", "SLAVE", "SLEDS", "SLEEK", "SLEEP",
    "SLEET", "SLEPT", "SLICE", "SLICK", "SLIDE", "SLIME", "SLIMY", "SLING", "SLINK", "SLIPS",
    "SLITS", "SLOGS", "SLOOP", "SLOPE", "SLOSH", "SLOTH", "SLOTS", "SLOWLY", "SLUGS", "SLUMP",
    "SLUMS", "SLUNG", "SLUNK", "SLURP", "SLURS", "SLUTS", "SLYLY", "SMACK", "SMALL", "SMART",
    "SMASH", "SMEAR", "SMELL", "SMELT", "SMILE", "SMIRK", "SMITE", "SMITH", "SMOCK", "SMOKE",
    "SMOKY", "SMOTE", "SNACK", "SNAIL", "SNAKE", "SNAKY", "SNAPS", "SNARE", "SNARL", "SNEAK",
    "SNEER", "SNIDE", "SNIFF", "SNIPE", "SNIPS", "SNITS", "SNOBS", "SNOOP", "SNORE", "SNORT",
    "SNOTS", "SNOUT", "SNOWS", "SNOWY", "SNUCK", "SNUFF", "SOAPY", "SOARS", "SOBER", "SOCKS",
    "SOILS", "SOLAR", "SOLDS", "SOLID", "SOLVE", "SONAR", "SONGS", "SONIC", "SONNY", "SOOTH",
    "SOOTS", "SORRY", "SORTS", "SOULS", "SOUND", "SOUPY", "SOUTH", "SOWER", "SPACE", "SPADE",
    "SPANK", "SPARE", "SPARK", "SPARS", "SPASM", "SPATE", "SPATS", "SPAWN", "SPAYS", "SPEAK",
    "SPEAR", "SPECK", "SPECS", "SPEED", "SPELL", "SPELT", "SPEND", "SPENT", "SPERM", "SPICE",
    "SPICY", "SPIED", "SPIES", "SPIKE", "SPIKY", "SPILL", "SPILT", "SPINE", "SPINS", "SPINY",
    "SPIRE", "SPITE", "SPITS", "SPLIT", "SPOIL", "SPOKE", "SPOOF", "SPOOK", "SPOOL", "SPOON",
    "SPORE", "SPORT", "SPOTS", "SPOUT", "SPRAT", "SPRAY", "SPREE", "SPRIG", "SPUNK", "SPURN",
    "SPURS", "SPURT", "SQUAB", "SQUAD", "SQUAT", "SQUID", "STABS", "STACK", "STAFF", "STAGE",
    "STAID", "STAIR", "STAKE", "STALE", "STALK", "STALL", "STAMP", "STAND", "STANK", "STARE",
    "STARK", "STARS", "START", "STASH", "STATE", "STATS", "STAVE", "STEAD", "STEAK", "STEAL",
    "STEAM", "STEEL", "STICK", "STILL", "STILT", "STING", "STINK", "STINT", "STIRS", "STOKE",
    "STOLE", "STOMP", "STONE", "STOOD", "STOOL", "STORE", "STORK", "STORM", "STORY", "STRIP",
    "STUCK", "STUDY", "STUFF", "STYLE", "SUAVE", "SUCKS", "SUCKY", "SUGAR", "SUING", "SUITE",
    "SUITS", "SULKY", "SULLY", "SUMAC", "SUNNY", "SUNUP", "SUPER", "SURER", "SURGE", "SURLY",
    "SUSHI", "SWAMI", "SWAMP", "SWANK", "SWANS", "SWAPS", "SWARM", "SWATS", "SWAYS", "SWEAR",
    "SWEAT", "SWEEP", "SWEET", "SWELL", "SWEPT", "SWIFT", "SWILL", "SWIMS", "SWINE", "SWING",
    "SWIRL", "SWISH", "SWOON", "SWOOP", "SWORD", "SWORE", "SWORN", "SWUNG", "SYRUP", "TABBY",
    "TABLE", "TABOO", "TACIT", "TACKS", "TACKY", "TAFFY", "TAILS", "TAINT", "TAKEN", "TAKER",
    "TAKES", "TALES", "TALKS", "TALKY", "TALLY", "TALON", "TAMED", "TAMER", "TAMES", "TANGO",
    "TANKS", "TAPED", "TAPES", "TAPIR", "TARDY", "TAROT", "TARTS", "TASKS", "TASTE", "TASTY",
    "TATTY", "TAUNT", "TAWNY", "TAXED", "TAXES", "TAXIS", "TEACH", "TEAMS", "TEARS", "TEARY",
    "TEASE", "TEATS", "TECHS", "TEENS", "TEENY", "TEETH", "TELEX", "TELLT", "TELLS", "TEMPO",
    "TEMPT", "TENDS", "TENET", "TENOR", "TENSE", "TENTH", "TENTS", "TEPEE", "TEPID", "TERMS",
    "TERRA", "TERSE", "TESTS", "TESTY", "TETRA", "TEXAS", "TEXTS", "THANK", "THATS", "THEFT",
    "THEIR", "THEME", "THERE", "THESE", "THICK", "THIEF", "THIGH", "THINE", "THING", "THINK",
    "THIRD", "THONG", "THORN", "THOSE", "THREE", "THREW", "THROB", "THROW", "THRUM", "THUMB",
    "THUMP", "THYME", "TIARA", "TIBET", "TICKS", "TIDAL", "TIDED", "TIDES", "TIERS", "TIGER",
    "TIGHT", "TILES", "TIMED", "TIMER", "TIMES", "TIMID", "TINES", "TINGE", "TINGS", "TINTS",
    "TINY", "TIPSY", "TIRED", "TIRES", "TITLE", "TOADS", "TOADY", "TOAST", "TODAY", "TOEFL",
    "TOGAS", "TOILS", "TOKEN", "TONAL", "TONED", "TONER", "TONES", "TONGS", "TONIC", "TOOLS",
    "TOOTH", "TOPAZ", "TOPIC", "TORCH", "TORSO", "TORUS", "TOTAL", "TOTED", "TOTEM", "TOUCH",
    "TOUGH", "TOURS", "TOWED", "TOWEL", "TOWER", "TOWNS", "TOXIC", "TOXIN", "TOYED", "TRACE",
    "TRACK", "TRACT", "TRADE", "TRAIL", "TRAIN", "TRAIT", "TRAMP", "TRAPS", "TRASH", "TRAWL",
    "TREAD", "TREAT", "TREES", "TREND", "TRIAD", "TRIAL", "TRIBE", "TRICK", "TRIED", "TRIER",
    "TRIES", "TRILL", "TRIMS", "TRIAD", "TRIPS", "TRITE", "TROLL", "TROOP", "TROPE", "TROUT",
    "TROVE", "TRUCE", "TRUCK", "TRUED", "TRUER", "TRUES", "TRUMP", "TRUNK", "TRUSS", "TRUST",
    "TRUTH", "TRYST", "TUBBY", "TUBER", "TUBES", "TUCKS", "TUFFS", "TULIP", "TULLE", "TUMOR",
    "TUNED", "TUNER", "TUNES", "TUNIC", "TURBO", "TURDS", "TURFY", "TURNS", "TUSKS", "TUTOR",
    "TUTUS", "TUXES", "TWAIN", "TWANG", "TWEED", "TWEEN", "TWEET", "TWICE", "TWIGS", "TWILL",
    "TWINE", "TWINS", "TWIRL", "TWIST", "TYING", "TYKES", "TYPED", "TYPES", "TYRES", "ULCER",
    "ULTRA", "UMBRA", "UNCLE", "UNCUT", "UNDER", "UNDID", "UNDUE", "UNFED", "UNFIT", "UNIFY",
    "UNION", "UNITE", "UNITS", "UNITY", "UNMET", "UNTIE", "UNTIL", "UNWED", "UNZIP", "UPPED",
    "UPPER", "UPSET", "URBAN", "USAGE", "USERS", "USHER", "USING", "USUAL", "USURP", "UTILE",
    "UTTER", "VAGUE", "VALET", "VALID", "VALOR", "VALUE", "VALVE", "VAPID", "VAPOR", "VAULT",
    "VAUNT", "VEGAN", "VEILS", "VEINS", "VELDT", "VENAL", "VENDS", "VENOM", "VENTS", "VENUE",
    "VERBS", "VERGE", "VERSE", "VERVE", "VESTS", "VEXED", "VEXES", "VIALS", "VIBES", "VICAR",
    "VICES", "VIDEO", "VIEWS", "VIGIL", "VIGOR", "VILLA", "VINYL", "VIOLA", "VIPER", "VIRAL",
    "VIRUS", "VISAS", "VISIT", "VISOR", "VISTA", "VITAL", "VIVID", "VIXEN", "VOCAL", "VODKA",
    "VOGUE", "VOICE", "VOIDS", "VOLTS", "VOMIT", "VOTED", "VOTER", "VOTES", "VOUCH", "VOWED",
    "VOWEL", "WACKY", "WADER", "WAFER", "WAGED", "WAGER", "WAGES", "WAGON", "WAIFS", "WAILS",
    "WAIST", "WAITS", "WAIVE", "WAKED", "WAKEN", "WAKES", "WALKS", "WALLS", "WALTZ", "WANDS",
    "WANED", "WANES", "WANTS", "WARDS", "WARES", "WARMS", "WARNS", "WARTS", "WASHY", "WASPS",
    "WASTE", "WATCH", "WATER", "WAVER", "WAVES", "WAXED", "WAXEN", "WAXES", "WEARS", "WEARY",
    "WEAVE", "WEDGE", "WEEDS", "WEEKS", "WEIGH", "WEIRD", "WELCH", "WELDS", "WELLS", "WELSH",
    "WENCH", "WHACK", "WHALE", "WHARF", "WHEAT", "WHEEL", "WHELP", "WHERE", "WHICH", "WHIFF",
    "WHILE", "WHIMS", "WHINE", "WHIPS", "WHIRL", "WHISK", "WHITE", "WHOLE", "WHOOP", "WHORE",
    "WHOSE", "WIDEN", "WIDER", "WIDES", "WIDOW", "WIDTH", "WIELD", "WIGHT", "WILDS", "WILES",
    "WILLS", "WILLY", "WIMPS", "WIMPY", "WINCE", "WINCH", "WINDS", "WINDY", "WINED", "WINES",
    "WINGS", "WINKS", "WIPED", "WIPES", "WIRED", "WIRES", "WISER", "WISPS", "WISPY", "WITCH",
    "WITTY", "WIVES", "WOKEN", "WOMAN", "WOMEN", "WOODS", "WOODY", "WOOED", "WOOER", "WOOFS",
    "WOOZY", "WORDS", "WORDY", "WORKS", "WORLD", "WORMS", "WORMY", "WORRY", "WORSE", "WORST",
    "WORTH", "WOULD", "WOUND", "WOVEN", "WRAPS", "WRATH", "WREAK", "WRECK", "WRENS", "WREST",
    "WRING", "WRIST", "WRITE", "WRONG", "WROTE", "WRUNG", "WRYLY", "YACHT", "YANKS", "YARDS",
    "YARNS", "YAWED", "YAWLS", "YAWNS", "YEAHS", "YEARN", "YEARS", "YEAST", "YELLS", "YELPS",
    "YODEL", "YOKED", "YOKEL", "YOKES", "YOLKS", "YOUNG", "YOURS", "YOUTH", "YOWLS", "ZEBRA",
    "ZEROS", "ZESTS", "ZESTY", "ZONED", "ZONES", "ZONKS"
]

WORDS = ["REACT", "PYTHON", "SMART", "CLOUD", "LOGIC", "PLATE", "SMILE"]

import hashlib
from datetime import datetime

def get_daily_word(game_id=None, user_id=None, db=None):
    """Get the daily word based on current date or game session, ensuring uniqueness for users"""
    today = datetime.utcnow().date()
    date_string = today.isoformat()

    # If game_id is provided, use it for unique word selection per game
    if game_id:
        date_string += game_id

    # For logged-in users, ensure the word hasn't been used before
    if user_id and db:
        used_words = db.query(UsedWords.word).filter(UsedWords.user_id == user_id).all()
        used_word_set = {word[0] for word in used_words}

        # Keep trying different hashes until we find an unused word
        attempt = 0
        while attempt < len(DAILY_ANSWERS):
            attempt_date_string = date_string + str(attempt)
            hash_object = hashlib.md5(attempt_date_string.encode())
            hash_int = int(hash_object.hexdigest(), 16)
            word_index = hash_int % len(DAILY_ANSWERS)
            candidate_word = DAILY_ANSWERS[word_index]

            if candidate_word not in used_word_set:
                return candidate_word

            attempt += 1

        # If all words have been used (unlikely but possible), return the first one
        return DAILY_ANSWERS[0]
    else:
        # For non-logged-in users, use the original logic
        hash_object = hashlib.md5(date_string.encode())
        hash_int = int(hash_object.hexdigest(), 16)
        word_index = hash_int % len(DAILY_ANSWERS)
        return DAILY_ANSWERS[word_index]

@app.get("/api/wordle/daily-word")
async def get_daily_word_endpoint(gameId: str = None, request: Request = None, db: Session = Depends(get_db)):
    # Get user_id if logged in
    user_id = None
    if request:
        session_id = request.cookies.get("session_id")
        if session_id:
            user = db.query(User).filter(User.id == int(session_id)).first()
            if user:
                user_id = user.id

    word = get_daily_word(gameId, user_id, db)
    return {"word": word}

@app.get("/api/wordle/next-reset")
async def get_next_reset():
    # Placeholder for the time remaining until the next word (in seconds)
    return {"time_remaining_seconds": 3600}

@app.post("/api/wordle/guess")
async def verify_guess(payload: dict, request: Request, db: Session = Depends(get_db)):
    guess = payload.get("guess", "").upper()
    game_id = payload.get("gameId")
    
    if len(guess) != 5:
        return {"error": "Guess must be exactly 5 letters"}
    
    # Check if the word exists in our comprehensive list
    if guess not in VALID_GUESSES:
        # We return a specific error message that the frontend will catch
        return {"error": "NOT_A_VALID_WORD"}
    
    # Get user_id if logged in
    user_id = None
    session_id = request.cookies.get("session_id")
    if session_id:
        user = db.query(User).filter(User.id == int(session_id)).first()
        if user:
            user_id = user.id
    
    target_word = get_daily_word(game_id, user_id, db)
    
    # Simple logic for status array
    status_array = []
    for i, char in enumerate(guess):
        if char == target_word[i]:
            status_array.append("correct")
        elif char in target_word:
            status_array.append("present")
        else:
            status_array.append("absent")
            
    return {
        "status_array": status_array,
        "is_correct": guess == target_word
    }

from pydantic import BaseModel
from datetime import datetime, timedelta

# ... existing code ...

class GameResult(BaseModel):
    won: bool
    points: int
    word: str  # Add word to track used words

# ... existing code ...

@app.post("/api/user/update-stats")
async def update_stats(result: GameResult, request: Request, db: Session = Depends(get_db)):
    session_id = request.cookies.get("session_id")
    if not session_id:
        return {"error": "Not logged in"}

    user = db.query(User).filter(User.id == int(session_id)).first()
    if not user:
        return {"error": "User not found"}

    stats = user.stats
    if not stats:
        # Create stats if not exists
        stats = UserStats(user_id=user.id)
        db.add(stats)
        db.commit()
        db.refresh(stats)

    today = datetime.utcnow().date()
    yesterday = today - timedelta(days=1)

    # Update games played
    stats.games_played += 1

    # Update points
    stats.total_points += result.points

    # Update win stats
    if result.won:
        stats.games_won += 1
        # Check streak
        if stats.last_played_date and stats.last_played_date.date() == yesterday:
            stats.current_streak += 1
        else:
            stats.current_streak = 1
        if stats.current_streak > stats.max_streak:
            stats.max_streak = stats.current_streak
    else:
        stats.current_streak = 0

    stats.last_played_date = datetime.utcnow()

    # Track the word that was used in this game
    used_word = UsedWords(user_id=user.id, word=result.word.upper())
    db.add(used_word)

    db.commit()

    return {"message": "Stats updated"}

@app.get("/api/user/stats")
async def get_stats(request: Request, db: Session = Depends(get_db)):
    session_id = request.cookies.get("session_id")
    
    if not session_id:
        return {
            "times_played": 0,
            "streak": 0,
            "max_streak": 0,
            "win_percentage": 0,
            "total_points": 0,
            "is_logged_in": False
        }

    user = db.query(User).filter(User.id == int(session_id)).first()
    if not user:
        return {"error": "User not found"}

    stats = user.stats
    if not stats:
        return {
            "username": user.username,
            "times_played": 0,
            "streak": 0,
            "max_streak": 0,
            "win_percentage": 0,
            "total_points": 0,
            "is_logged_in": True
        }

    win_percentage = (stats.games_won / stats.games_played * 100) if stats.games_played > 0 else 0

    is_ongoing = stats.last_played_date and stats.last_played_date.date() == datetime.utcnow().date() and stats.current_streak > 0

    return {
        "username": user.username,
        "times_played": stats.games_played,
        "streak": stats.current_streak,
        "max_streak": stats.max_streak,
        "win_percentage": round(win_percentage, 2),
        "total_points": stats.total_points,
        "currentStreakOngoing": is_ongoing,
        "is_logged_in": True
    }

@app.get("/")
async def root():
    return {"message": "Quickle API is running"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
